/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package pl.postivo.sdk;

import static pl.postivo.sdk.operations.Operations.RequestlessOperation;
import static pl.postivo.sdk.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Exception;
import java.lang.String;
import pl.postivo.sdk.models.operations.GetAccountDetailsRequestBuilder;
import pl.postivo.sdk.models.operations.GetAccountDetailsResponse;
import pl.postivo.sdk.models.operations.GetSubaccountDetailsRequest;
import pl.postivo.sdk.models.operations.GetSubaccountDetailsRequestBuilder;
import pl.postivo.sdk.models.operations.GetSubaccountDetailsResponse;
import pl.postivo.sdk.operations.GetAccountDetails;
import pl.postivo.sdk.operations.GetSubaccountDetails;
import pl.postivo.sdk.utils.Headers;
import pl.postivo.sdk.utils.Options;


public class Accounts {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncAccounts asyncSDK;

    Accounts(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncAccounts(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncAccounts async() {
        return asyncSDK;
    }

    /**
     * Retrieve account details
     * 
     * <p>Retrieve the current account balance and other account details. You can also check the account limit
     * and whether the account is a **main** account. Main accounts have unrestricted privileges and, via
     * the [User Panel](https://panel.postivo.pl), you can create as many subaccounts as needed.
     * 
     * @return The call builder
     */
    public GetAccountDetailsRequestBuilder get() {
        return new GetAccountDetailsRequestBuilder(sdkConfiguration);
    }

    /**
     * Retrieve account details
     * 
     * <p>Retrieve the current account balance and other account details. You can also check the account limit
     * and whether the account is a **main** account. Main accounts have unrestricted privileges and, via
     * the [User Panel](https://panel.postivo.pl), you can create as many subaccounts as needed.
     * 
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public GetAccountDetailsResponse getDirect() throws Exception {
        return get(null);
    }

    /**
     * Retrieve account details
     * 
     * <p>Retrieve the current account balance and other account details. You can also check the account limit
     * and whether the account is a **main** account. Main accounts have unrestricted privileges and, via
     * the [User Panel](https://panel.postivo.pl), you can create as many subaccounts as needed.
     * 
     * @param options additional options
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public GetAccountDetailsResponse get(@Nullable Options options) throws Exception {
        RequestlessOperation<GetAccountDetailsResponse> operation
            = new GetAccountDetails.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest());
    }

    /**
     * Get subaccount details
     * 
     * <p>Check the account balance and other details, such as the subcredit balance of a subaccount.
     * Subaccounts are additional users who can access your account’s services and data. You can restrict
     * access levels and set privileges for subaccounts in the [User Panel](https://panel.postivo.pl).
     * 
     * <p>Provide the full subaccount login to access its data.
     * 
     * @return The call builder
     */
    public GetSubaccountDetailsRequestBuilder getSubaccount() {
        return new GetSubaccountDetailsRequestBuilder(sdkConfiguration);
    }

    /**
     * Get subaccount details
     * 
     * <p>Check the account balance and other details, such as the subcredit balance of a subaccount.
     * Subaccounts are additional users who can access your account’s services and data. You can restrict
     * access levels and set privileges for subaccounts in the [User Panel](https://panel.postivo.pl).
     * 
     * <p>Provide the full subaccount login to access its data.
     * 
     * @param userLogin Login of the subaccount (user) for which to retrieve data.
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public GetSubaccountDetailsResponse getSubaccount(@Nonnull String userLogin) throws Exception {
        return getSubaccount(userLogin, null);
    }

    /**
     * Get subaccount details
     * 
     * <p>Check the account balance and other details, such as the subcredit balance of a subaccount.
     * Subaccounts are additional users who can access your account’s services and data. You can restrict
     * access levels and set privileges for subaccounts in the [User Panel](https://panel.postivo.pl).
     * 
     * <p>Provide the full subaccount login to access its data.
     * 
     * @param userLogin Login of the subaccount (user) for which to retrieve data.
     * @param options additional options
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public GetSubaccountDetailsResponse getSubaccount(@Nonnull String userLogin, @Nullable Options options) throws Exception {
        GetSubaccountDetailsRequest request = new GetSubaccountDetailsRequest(userLogin);
        RequestOperation<GetSubaccountDetailsRequest, GetSubaccountDetailsResponse> operation
              = new GetSubaccountDetails.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
