/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package pl.postivo.sdk;

import pl.postivo.sdk.utils.Headers;


public class AddressBook {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncAddressBook asyncSDK;
    private final Contacts contacts;
    private final Groups groups;

    AddressBook(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.contacts = new Contacts(this.sdkConfiguration);
        this.groups = new Groups(this.sdkConfiguration);
        this.asyncSDK = new AsyncAddressBook(this, sdkConfiguration);
    }

    public final Contacts contacts() {
        return contacts;
    }

    public final Groups groups() {
        return groups;
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncAddressBook async() {
        return asyncSDK;
    }

}
