/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package pl.postivo.sdk;

import pl.postivo.sdk.utils.Headers;

public class AsyncClient {
    private static final Headers _headers = Headers.EMPTY;

    private final AsyncAccounts accounts;

    private final AsyncAddressBook addressBook;

    private final AsyncShipments shipments;

    private final AsyncMetadata metadata;
    /**
     * Common
     */
    private final AsyncCommon common;

    private final AsyncSenders senders;

    public AsyncAccounts accounts() {
        return accounts;
    }

    public AsyncAddressBook addressBook() {
        return addressBook;
    }

    public AsyncShipments shipments() {
        return shipments;
    }

    public AsyncMetadata metadata() {
        return metadata;
    }
    /**
     * Common
     */
    public AsyncCommon common() {
        return common;
    }

    public AsyncSenders senders() {
        return senders;
    }

    private SDKConfiguration sdkConfiguration;
    private final Client syncSDK;

    AsyncClient(Client syncSDK, SDKConfiguration sdkConfiguration) {
        this.syncSDK = syncSDK;
        this.sdkConfiguration = sdkConfiguration;
        this.accounts = new AsyncAccounts(syncSDK.accounts(), sdkConfiguration);
        this.addressBook = new AsyncAddressBook(syncSDK.addressBook(), sdkConfiguration);
        this.shipments = new AsyncShipments(syncSDK.shipments(), sdkConfiguration);
        this.metadata = new AsyncMetadata(syncSDK.metadata(), sdkConfiguration);
        this.common = new AsyncCommon(syncSDK.common(), sdkConfiguration);
        this.senders = new AsyncSenders(syncSDK.senders(), sdkConfiguration);
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public Client sync() {
        return syncSDK;
    }
}
