/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package pl.postivo.sdk;

import pl.postivo.sdk.utils.Headers;


public class AsyncAddressBook {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncContacts contacts;
    private final AsyncGroups groups;
    private final AddressBook syncSDK;

    AsyncAddressBook(AddressBook syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.contacts = new AsyncContacts(syncSDK.contacts(), this.sdkConfiguration);
        this.groups = new AsyncGroups(syncSDK.groups(), this.sdkConfiguration);
        this.syncSDK = syncSDK;
    }

    public final AsyncContacts contacts() {
        return contacts;
    }

    public final AsyncGroups groups() {
        return groups;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public AddressBook sync() {
        return syncSDK;
    }

}
