/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package pl.postivo.sdk;

import static pl.postivo.sdk.operations.Operations.AsyncRequestlessOperation;

import jakarta.annotation.Nullable;
import java.util.concurrent.CompletableFuture;
import pl.postivo.sdk.models.operations.async.ListMetadataRequestBuilder;
import pl.postivo.sdk.models.operations.async.ListMetadataResponse;
import pl.postivo.sdk.models.operations.async.ListPredefinedConfigsRequestBuilder;
import pl.postivo.sdk.models.operations.async.ListPredefinedConfigsResponse;
import pl.postivo.sdk.operations.ListMetadata;
import pl.postivo.sdk.operations.ListPredefinedConfigs;
import pl.postivo.sdk.utils.Headers;
import pl.postivo.sdk.utils.Options;


public class AsyncMetadata {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final Metadata syncSDK;

    AsyncMetadata(Metadata syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public Metadata sync() {
        return syncSDK;
    }


    /**
     * List metadata
     * 
     * <p>Retrieve a complete list of all types for shipments and their possible values. The method has no
     * body and takes no parameters. The response includes metadata such as carrier types, service types,
     * and more.
     * 
     * @return The async call builder
     */
    public ListMetadataRequestBuilder list() {
        return new ListMetadataRequestBuilder(sdkConfiguration);
    }

    /**
     * List metadata
     * 
     * <p>Retrieve a complete list of all types for shipments and their possible values. The method has no
     * body and takes no parameters. The response includes metadata such as carrier types, service types,
     * and more.
     * 
     * @return {@code CompletableFuture<ListMetadataResponse>} - The async response
     */
    public CompletableFuture<ListMetadataResponse> listDirect() {
        return list(null);
    }

    /**
     * List metadata
     * 
     * <p>Retrieve a complete list of all types for shipments and their possible values. The method has no
     * body and takes no parameters. The response includes metadata such as carrier types, service types,
     * and more.
     * 
     * @param options additional options
     * @return {@code CompletableFuture<ListMetadataResponse>} - The async response
     */
    public CompletableFuture<ListMetadataResponse> list(@Nullable Options options) {
        AsyncRequestlessOperation<ListMetadataResponse> operation
            = new ListMetadata.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest()
            .thenCompose(operation::handleResponse);
    }


    /**
     * List predefined configs
     * 
     * <p>Retrieve a complete list of predefined shipment configurations. The method has no body and takes no
     * parameters. The response includes all stored configuration options.
     * 
     * @return The async call builder
     */
    public ListPredefinedConfigsRequestBuilder getPredefinedConfigs() {
        return new ListPredefinedConfigsRequestBuilder(sdkConfiguration);
    }

    /**
     * List predefined configs
     * 
     * <p>Retrieve a complete list of predefined shipment configurations. The method has no body and takes no
     * parameters. The response includes all stored configuration options.
     * 
     * @return {@code CompletableFuture<ListPredefinedConfigsResponse>} - The async response
     */
    public CompletableFuture<ListPredefinedConfigsResponse> getPredefinedConfigsDirect() {
        return getPredefinedConfigs(null);
    }

    /**
     * List predefined configs
     * 
     * <p>Retrieve a complete list of predefined shipment configurations. The method has no body and takes no
     * parameters. The response includes all stored configuration options.
     * 
     * @param options additional options
     * @return {@code CompletableFuture<ListPredefinedConfigsResponse>} - The async response
     */
    public CompletableFuture<ListPredefinedConfigsResponse> getPredefinedConfigs(@Nullable Options options) {
        AsyncRequestlessOperation<ListPredefinedConfigsResponse> operation
            = new ListPredefinedConfigs.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest()
            .thenCompose(operation::handleResponse);
    }

}
