/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package pl.postivo.sdk;

import static pl.postivo.sdk.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import pl.postivo.sdk.models.components.Shipment;
import pl.postivo.sdk.models.operations.CancelShipmentRequest;
import pl.postivo.sdk.models.operations.DocumentType;
import pl.postivo.sdk.models.operations.GetDocumentsRequest;
import pl.postivo.sdk.models.operations.GetStatusRequest;
import pl.postivo.sdk.models.operations.async.CancelShipmentRequestBuilder;
import pl.postivo.sdk.models.operations.async.CancelShipmentResponse;
import pl.postivo.sdk.models.operations.async.GetDocumentsRequestBuilder;
import pl.postivo.sdk.models.operations.async.GetDocumentsResponse;
import pl.postivo.sdk.models.operations.async.GetStatusRequestBuilder;
import pl.postivo.sdk.models.operations.async.GetStatusResponse;
import pl.postivo.sdk.models.operations.async.ShipmentDispatchRequestBuilder;
import pl.postivo.sdk.models.operations.async.ShipmentDispatchResponse;
import pl.postivo.sdk.models.operations.async.ShipmentPriceRequestBuilder;
import pl.postivo.sdk.models.operations.async.ShipmentPriceResponse;
import pl.postivo.sdk.operations.CancelShipment;
import pl.postivo.sdk.operations.GetDocuments;
import pl.postivo.sdk.operations.GetStatus;
import pl.postivo.sdk.operations.ShipmentDispatch;
import pl.postivo.sdk.operations.ShipmentPrice;
import pl.postivo.sdk.utils.Headers;
import pl.postivo.sdk.utils.Options;


public class AsyncShipments {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final Shipments syncSDK;

    AsyncShipments(Shipments syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public Shipments sync() {
        return syncSDK;
    }


    /**
     * Retrieve shipment details with status events
     * 
     * <p>Retrieve the current status and details for one or more shipments by their `ids`. Pass the unique
     * shipment IDs (returned when the shipments were created) as a path parameter. To query provide a list
     * (up to **50** IDs per call).
     * 
     * <p>For larger batches, split the requests.
     * 
     * @return The async call builder
     */
    public GetStatusRequestBuilder status() {
        return new GetStatusRequestBuilder(sdkConfiguration);
    }

    /**
     * Retrieve shipment details with status events
     * 
     * <p>Retrieve the current status and details for one or more shipments by their `ids`. Pass the unique
     * shipment IDs (returned when the shipments were created) as a path parameter. To query provide a list
     * (up to **50** IDs per call).
     * 
     * <p>For larger batches, split the requests.
     * 
     * @param ids Shipment IDs assigned by the system (comma-separated). The system accepts a maximum of **50** identifiers per call.
     * @return {@code CompletableFuture<GetStatusResponse>} - The async response
     */
    public CompletableFuture<GetStatusResponse> status(@Nonnull List<String> ids) {
        return status(ids, null);
    }

    /**
     * Retrieve shipment details with status events
     * 
     * <p>Retrieve the current status and details for one or more shipments by their `ids`. Pass the unique
     * shipment IDs (returned when the shipments were created) as a path parameter. To query provide a list
     * (up to **50** IDs per call).
     * 
     * <p>For larger batches, split the requests.
     * 
     * @param ids Shipment IDs assigned by the system (comma-separated). The system accepts a maximum of **50** identifiers per call.
     * @param options additional options
     * @return {@code CompletableFuture<GetStatusResponse>} - The async response
     */
    public CompletableFuture<GetStatusResponse> status(@Nonnull List<String> ids, @Nullable Options options) {
        GetStatusRequest request = new GetStatusRequest(ids);
        AsyncRequestOperation<GetStatusRequest, GetStatusResponse> operation
              = new GetStatus.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Cancel shipments
     * 
     * <p>Cancel shipments that have not yet been processed by their `ids`. Pass the unique shipment IDs
     * (returned when the shipment was created) as a parameter. To cancel multiple shipments at once,
     * provide a list of IDs (up to **50** per call).
     * 
     * <p>For larger volumes, split the operation into multiple requests. Only shipments with status
     * `ACCEPTED` can be cancelled.
     * 
     * <p>If duplicate shipment IDs are provided in a single call, the API processes each unique ID only once.
     * 
     * @return The async call builder
     */
    public CancelShipmentRequestBuilder cancel() {
        return new CancelShipmentRequestBuilder(sdkConfiguration);
    }

    /**
     * Cancel shipments
     * 
     * <p>Cancel shipments that have not yet been processed by their `ids`. Pass the unique shipment IDs
     * (returned when the shipment was created) as a parameter. To cancel multiple shipments at once,
     * provide a list of IDs (up to **50** per call).
     * 
     * <p>For larger volumes, split the operation into multiple requests. Only shipments with status
     * `ACCEPTED` can be cancelled.
     * 
     * <p>If duplicate shipment IDs are provided in a single call, the API processes each unique ID only once.
     * 
     * @param ids Shipment IDs assigned by the system (comma-separated). The system accepts a maximum of **50** identifiers per call.
     * @return {@code CompletableFuture<CancelShipmentResponse>} - The async response
     */
    public CompletableFuture<CancelShipmentResponse> cancel(@Nonnull List<String> ids) {
        return cancel(ids, null);
    }

    /**
     * Cancel shipments
     * 
     * <p>Cancel shipments that have not yet been processed by their `ids`. Pass the unique shipment IDs
     * (returned when the shipment was created) as a parameter. To cancel multiple shipments at once,
     * provide a list of IDs (up to **50** per call).
     * 
     * <p>For larger volumes, split the operation into multiple requests. Only shipments with status
     * `ACCEPTED` can be cancelled.
     * 
     * <p>If duplicate shipment IDs are provided in a single call, the API processes each unique ID only once.
     * 
     * @param ids Shipment IDs assigned by the system (comma-separated). The system accepts a maximum of **50** identifiers per call.
     * @param options additional options
     * @return {@code CompletableFuture<CancelShipmentResponse>} - The async response
     */
    public CompletableFuture<CancelShipmentResponse> cancel(@Nonnull List<String> ids, @Nullable Options options) {
        CancelShipmentRequest request = new CancelShipmentRequest(ids);
        AsyncRequestOperation<CancelShipmentRequest, CancelShipmentResponse> operation
              = new CancelShipment.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Dispatch a new shipment
     * 
     * <p>Send a shipment to one or multiple recipients in a single request. Provide a `Shipment` object. The
     * object includes properties that define the shipment (recipient details, included documents, and
     * optional settings).
     * 
     * <p>Some fields are required.
     * 
     * <p>The system accepts up to **50** recipients per call. For larger volumes, split the operation into
     * multiple requests.
     * 
     * @return The async call builder
     */
    public ShipmentDispatchRequestBuilder dispatch() {
        return new ShipmentDispatchRequestBuilder(sdkConfiguration);
    }

    /**
     * Dispatch a new shipment
     * 
     * <p>Send a shipment to one or multiple recipients in a single request. Provide a `Shipment` object. The
     * object includes properties that define the shipment (recipient details, included documents, and
     * optional settings).
     * 
     * <p>Some fields are required.
     * 
     * <p>The system accepts up to **50** recipients per call. For larger volumes, split the operation into
     * multiple requests.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<ShipmentDispatchResponse>} - The async response
     */
    public CompletableFuture<ShipmentDispatchResponse> dispatch(@Nonnull Shipment request) {
        return dispatch(request, null);
    }

    /**
     * Dispatch a new shipment
     * 
     * <p>Send a shipment to one or multiple recipients in a single request. Provide a `Shipment` object. The
     * object includes properties that define the shipment (recipient details, included documents, and
     * optional settings).
     * 
     * <p>Some fields are required.
     * 
     * <p>The system accepts up to **50** recipients per call. For larger volumes, split the operation into
     * multiple requests.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<ShipmentDispatchResponse>} - The async response
     */
    public CompletableFuture<ShipmentDispatchResponse> dispatch(@Nonnull Shipment request, @Nullable Options options) {
        AsyncRequestOperation<Shipment, ShipmentDispatchResponse> operation
              = new ShipmentDispatch.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Retrieve documents related to a shipment
     * 
     * <p>Download documents related to a shipment by its `id`. Pass the unique shipment `id` (returned when
     * the shipment was created) as a parameter. The second parameter is the document type to download.
     * 
     * <p>Supported document types include: dispatch certificate, envelope template, and EPO (in PDF or XML
     * formats).
     * 
     * @return The async call builder
     */
    public GetDocumentsRequestBuilder documents() {
        return new GetDocumentsRequestBuilder(sdkConfiguration);
    }

    /**
     * Retrieve documents related to a shipment
     * 
     * <p>Download documents related to a shipment by its `id`. Pass the unique shipment `id` (returned when
     * the shipment was created) as a parameter. The second parameter is the document type to download.
     * 
     * <p>Supported document types include: dispatch certificate, envelope template, and EPO (in PDF or XML
     * formats).
     * 
     * @param id Single shipment ID assigned by the system when the shipment was created.
     * @param type Type of document/certificate to generate.
     * @return {@code CompletableFuture<GetDocumentsResponse>} - The async response
     */
    public CompletableFuture<GetDocumentsResponse> documents(@Nonnull String id, @Nonnull DocumentType type) {
        return documents(id, type, null);
    }

    /**
     * Retrieve documents related to a shipment
     * 
     * <p>Download documents related to a shipment by its `id`. Pass the unique shipment `id` (returned when
     * the shipment was created) as a parameter. The second parameter is the document type to download.
     * 
     * <p>Supported document types include: dispatch certificate, envelope template, and EPO (in PDF or XML
     * formats).
     * 
     * @param id Single shipment ID assigned by the system when the shipment was created.
     * @param type Type of document/certificate to generate.
     * @param options additional options
     * @return {@code CompletableFuture<GetDocumentsResponse>} - The async response
     */
    public CompletableFuture<GetDocumentsResponse> documents(
            @Nonnull String id, @Nonnull DocumentType type,
            @Nullable Options options) {
        GetDocumentsRequest request = new GetDocumentsRequest(id, type);
        AsyncRequestOperation<GetDocumentsRequest, GetDocumentsResponse> operation
              = new GetDocuments.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Check the shipment price
     * 
     * <p>Check the price of a shipment for one or multiple recipients. Provide a `Shipment` object in the
     * request. Each object includes properties such as recipient details, included documents, and optional
     * settings.
     * 
     * <p>Some fields are required.
     * 
     * <p>The system accepts up to **50** recipients per call. For larger volumes, split the operation into
     * multiple requests.
     * 
     * @return The async call builder
     */
    public ShipmentPriceRequestBuilder price() {
        return new ShipmentPriceRequestBuilder(sdkConfiguration);
    }

    /**
     * Check the shipment price
     * 
     * <p>Check the price of a shipment for one or multiple recipients. Provide a `Shipment` object in the
     * request. Each object includes properties such as recipient details, included documents, and optional
     * settings.
     * 
     * <p>Some fields are required.
     * 
     * <p>The system accepts up to **50** recipients per call. For larger volumes, split the operation into
     * multiple requests.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<ShipmentPriceResponse>} - The async response
     */
    public CompletableFuture<ShipmentPriceResponse> price(@Nonnull Shipment request) {
        return price(request, null);
    }

    /**
     * Check the shipment price
     * 
     * <p>Check the price of a shipment for one or multiple recipients. Provide a `Shipment` object in the
     * request. Each object includes properties such as recipient details, included documents, and optional
     * settings.
     * 
     * <p>Some fields are required.
     * 
     * <p>The system accepts up to **50** recipients per call. For larger volumes, split the operation into
     * multiple requests.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<ShipmentPriceResponse>} - The async response
     */
    public CompletableFuture<ShipmentPriceResponse> price(@Nonnull Shipment request, @Nullable Options options) {
        AsyncRequestOperation<Shipment, ShipmentPriceResponse> operation
              = new ShipmentPrice.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
