/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package pl.postivo.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import pl.postivo.sdk.utils.OneOfDeserializer;
import pl.postivo.sdk.utils.TypedObject;
import pl.postivo.sdk.utils.Utils.JsonShape;
import pl.postivo.sdk.utils.Utils.TypeReferenceWithShape;
import pl.postivo.sdk.utils.Utils;

/**
 * Documents
 * 
 * <p>A base document object.
 */
@JsonDeserialize(using = Documents._Deserializer.class)
public class Documents {

    @JsonValue
    private TypedObject value;
    
    private Documents(TypedObject value) {
        this.value = value;
    }

    public static Documents of(DocumentPdf value) {
        Utils.checkNotNull(value, "value");
        return new Documents(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<DocumentPdf>(){}));
    }

    public static Documents of(DocumentLibrary value) {
        Utils.checkNotNull(value, "value");
        return new Documents(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<DocumentLibrary>(){}));
    }

    public static Documents of(DocumentMock value) {
        Utils.checkNotNull(value, "value");
        return new Documents(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<DocumentMock>(){}));
    }
    
    /**
     * Returns an instance of one of these types:
     * <ul>
     * <li>{@code pl.postivo.sdk.models.components.DocumentPdf}</li>
     * <li>{@code pl.postivo.sdk.models.components.DocumentLibrary}</li>
     * <li>{@code pl.postivo.sdk.models.components.DocumentMock}</li>
     * </ul>
     * 
     * <p>Use {@code instanceof} to determine what type is returned. For example:
     * 
     * <pre>
     * if (obj.value() instanceof String) {
     *     String answer = (String) obj.value();
     *     System.out.println("answer=" + answer);
     * }
     * </pre>
     * 
     * @return value of oneOf type
     **/ 
    public java.lang.Object value() {
        return value.value();
    }    
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Documents other = (Documents) o;
        return Utils.enhancedDeepEquals(this.value.value(), other.value.value()); 
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(value.value());
    }
    
    @SuppressWarnings("serial")
    public static final class _Deserializer extends OneOfDeserializer<Documents> {

        public _Deserializer() {
            super(Documents.class, false,
                  TypeReferenceWithShape.of(new TypeReference<DocumentPdf>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<DocumentMock>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<DocumentLibrary>() {}, JsonShape.DEFAULT));
        }
    }
    
    @Override
    public String toString() {
        return Utils.toString(Documents.class,
                "value", value);
    }
 
}

