/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package pl.postivo.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;
import pl.postivo.sdk.utils.Utils;

/**
 * GroupResponse
 * 
 * <p>Address Book group details returned by the API.
 */
public class GroupResponse {
    /**
     * Group name.
     */
    @JsonProperty("name")
    private String name;

    /**
     * Optional group description.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("description")
    private JsonNullable<String> description;

    /**
     * Unique system-assigned group ID.
     */
    @JsonProperty("id")
    private long id;

    @JsonCreator
    public GroupResponse(
            @JsonProperty("name") @Nonnull String name,
            @JsonProperty("description") @Nullable JsonNullable<String> description,
            @JsonProperty("id") long id) {
        this.name = Optional.ofNullable(name)
            .orElseThrow(() -> new IllegalArgumentException("name cannot be null"));
        this.description = Optional.ofNullable(description)
            .orElse(JsonNullable.undefined());
        this.id = id;
    }
    
    public GroupResponse(
            @Nonnull String name,
            long id) {
        this(name, null, id);
    }

    /**
     * Group name.
     */
    public String name() {
        return this.name;
    }

    /**
     * Optional group description.
     */
    public JsonNullable<String> description() {
        return this.description;
    }

    /**
     * Unique system-assigned group ID.
     */
    public long id() {
        return this.id;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Group name.
     */
    public GroupResponse withName(@Nonnull String name) {
        this.name = Utils.checkNotNull(name, "name");
        return this;
    }


    /**
     * Optional group description.
     */
    public GroupResponse withDescription(@Nullable String description) {
        this.description = JsonNullable.of(description);
        return this;
    }


    /**
     * Unique system-assigned group ID.
     */
    public GroupResponse withId(long id) {
        this.id = id;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GroupResponse other = (GroupResponse) o;
        return 
            Utils.enhancedDeepEquals(this.name, other.name) &&
            Utils.enhancedDeepEquals(this.description, other.description) &&
            Utils.enhancedDeepEquals(this.id, other.id);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            name, description, id);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GroupResponse.class,
                "name", name,
                "description", description,
                "id", id);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String name;

        private JsonNullable<String> description;

        private long id;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Group name.
         */
        public Builder name(@Nonnull String name) {
            this.name = Utils.checkNotNull(name, "name");
            return this;
        }

        /**
         * Optional group description.
         */
        public Builder description(@Nullable String description) {
            this.description = JsonNullable.of(description);
            return this;
        }

        /**
         * Unique system-assigned group ID.
         */
        public Builder id(long id) {
            this.id = id;
            return this;
        }

        public GroupResponse build() {
            return new GroupResponse(
                name, description, id);
        }

    }
}
