/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package pl.postivo.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import pl.postivo.sdk.utils.OneOfDeserializer;
import pl.postivo.sdk.utils.TypedObject;
import pl.postivo.sdk.utils.Utils.JsonShape;
import pl.postivo.sdk.utils.Utils.TypeReferenceWithShape;
import pl.postivo.sdk.utils.Utils;

@JsonDeserialize(using = MiscInfoUnion._Deserializer.class)
public class MiscInfoUnion {

    @JsonValue
    private TypedObject value;
    
    private MiscInfoUnion(TypedObject value) {
        this.value = value;
    }

    public static MiscInfoUnion of(MiscInfo value) {
        Utils.checkNotNull(value, "value");
        return new MiscInfoUnion(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<MiscInfo>(){}));
    }
    
    /**
     * Returns an instance of one of these types:
     * <ul>
     * <li>{@code pl.postivo.sdk.models.components.MiscInfo}</li>
     * </ul>
     * 
     * <p>Use {@code instanceof} to determine what type is returned. For example:
     * 
     * <pre>
     * if (obj.value() instanceof String) {
     *     String answer = (String) obj.value();
     *     System.out.println("answer=" + answer);
     * }
     * </pre>
     * 
     * @return value of oneOf type
     **/ 
    public java.lang.Object value() {
        return value.value();
    }    
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MiscInfoUnion other = (MiscInfoUnion) o;
        return Utils.enhancedDeepEquals(this.value.value(), other.value.value()); 
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(value.value());
    }
    
    @SuppressWarnings("serial")
    public static final class _Deserializer extends OneOfDeserializer<MiscInfoUnion> {

        public _Deserializer() {
            super(MiscInfoUnion.class, false,
                  TypeReferenceWithShape.of(new TypeReference<MiscInfo>() {}, JsonShape.DEFAULT));
        }
    }
    
    @Override
    public String toString() {
        return Utils.toString(MiscInfoUnion.class,
                "value", value);
    }
 
}

