/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package pl.postivo.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;
import pl.postivo.sdk.utils.LazySingletonValue;
import pl.postivo.sdk.utils.Utils;

/**
 * RecipientInline
 * 
 * <p>Recipient data with full address for inline definition.
 */
public class RecipientInline {
    /**
     * Name (person or company) — line 1.
     */
    @JsonInclude(Include.ALWAYS)
    @JsonProperty("name")
    private JsonNullable<String> name;

    /**
     * Name (person or company) — line 2.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name2")
    private JsonNullable<String> name2;

    /**
     * Street address.
     */
    @JsonInclude(Include.ALWAYS)
    @JsonProperty("address")
    private JsonNullable<String> address;

    /**
     * Building number.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("home_number")
    private JsonNullable<String> homeNumber;

    /**
     * Apartment (unit) number.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("flat_number")
    private JsonNullable<String> flatNumber;

    /**
     * Postal code. For `PL`, 5-digit values are normalized to the `NN-NNN` format.
     */
    @JsonInclude(Include.ALWAYS)
    @JsonProperty("post_code")
    private JsonNullable<String> postCode;

    /**
     * City.
     */
    @JsonInclude(Include.ALWAYS)
    @JsonProperty("city")
    private JsonNullable<String> city;

    /**
     * Country code in ISO 3166-1 alpha-2 format. Default: "PL". Value is automatically uppercased.
     * 
     * <p>Full list: https://www.iso.org/iso-3166-country-codes.html
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("country")
    private JsonNullable<String> country;

    /**
     * Phone number (E.164 format recommended).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("phone_number")
    private JsonNullable<String> phoneNumber;

    /**
     * Optional postscript printed above the recipient data on the envelope.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("postscript")
    private JsonNullable<String> postscript;

    /**
     * Custom shipment identifier assigned by the user.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("custom_id")
    private JsonNullable<String> customId;

    @JsonCreator
    public RecipientInline(
            @JsonProperty("name") @Nullable String name,
            @JsonProperty("name2") @Nullable JsonNullable<String> name2,
            @JsonProperty("address") @Nullable String address,
            @JsonProperty("home_number") @Nullable JsonNullable<String> homeNumber,
            @JsonProperty("flat_number") @Nullable JsonNullable<String> flatNumber,
            @JsonProperty("post_code") @Nullable String postCode,
            @JsonProperty("city") @Nullable String city,
            @JsonProperty("country") @Nullable JsonNullable<String> country,
            @JsonProperty("phone_number") @Nullable JsonNullable<String> phoneNumber,
            @JsonProperty("postscript") @Nullable JsonNullable<String> postscript,
            @JsonProperty("custom_id") @Nullable JsonNullable<String> customId) {
        this.name = JsonNullable.of(name);
        this.name2 = Optional.ofNullable(name2)
            .orElse(JsonNullable.undefined());
        this.address = JsonNullable.of(address);
        this.homeNumber = Optional.ofNullable(homeNumber)
            .orElse(JsonNullable.undefined());
        this.flatNumber = Optional.ofNullable(flatNumber)
            .orElse(JsonNullable.undefined());
        this.postCode = JsonNullable.of(postCode);
        this.city = JsonNullable.of(city);
        this.country = Optional.ofNullable(country)
            .orElse(JsonNullable.of(Builder._SINGLETON_VALUE_Country.value()));
        this.phoneNumber = Optional.ofNullable(phoneNumber)
            .orElse(JsonNullable.undefined());
        this.postscript = Optional.ofNullable(postscript)
            .orElse(JsonNullable.undefined());
        this.customId = Optional.ofNullable(customId)
            .orElse(JsonNullable.of(Builder._SINGLETON_VALUE_CustomId.value()));
    }
    
    public RecipientInline() {
        this(null, null, null,
            null, null, null,
            null, null, null,
            null, null);
    }

    /**
     * Name (person or company) — line 1.
     */
    public JsonNullable<String> name() {
        return this.name;
    }

    /**
     * Name (person or company) — line 2.
     */
    public JsonNullable<String> name2() {
        return this.name2;
    }

    /**
     * Street address.
     */
    public JsonNullable<String> address() {
        return this.address;
    }

    /**
     * Building number.
     */
    public JsonNullable<String> homeNumber() {
        return this.homeNumber;
    }

    /**
     * Apartment (unit) number.
     */
    public JsonNullable<String> flatNumber() {
        return this.flatNumber;
    }

    /**
     * Postal code. For `PL`, 5-digit values are normalized to the `NN-NNN` format.
     */
    public JsonNullable<String> postCode() {
        return this.postCode;
    }

    /**
     * City.
     */
    public JsonNullable<String> city() {
        return this.city;
    }

    /**
     * Country code in ISO 3166-1 alpha-2 format. Default: "PL". Value is automatically uppercased.
     * 
     * <p>Full list: https://www.iso.org/iso-3166-country-codes.html
     */
    public JsonNullable<String> country() {
        return this.country;
    }

    /**
     * Phone number (E.164 format recommended).
     */
    public JsonNullable<String> phoneNumber() {
        return this.phoneNumber;
    }

    /**
     * Optional postscript printed above the recipient data on the envelope.
     */
    public JsonNullable<String> postscript() {
        return this.postscript;
    }

    /**
     * Custom shipment identifier assigned by the user.
     */
    public JsonNullable<String> customId() {
        return this.customId;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Name (person or company) — line 1.
     */
    public RecipientInline withName(@Nullable String name) {
        this.name = JsonNullable.of(name);
        return this;
    }


    /**
     * Name (person or company) — line 2.
     */
    public RecipientInline withName2(@Nullable String name2) {
        this.name2 = JsonNullable.of(name2);
        return this;
    }


    /**
     * Street address.
     */
    public RecipientInline withAddress(@Nullable String address) {
        this.address = JsonNullable.of(address);
        return this;
    }


    /**
     * Building number.
     */
    public RecipientInline withHomeNumber(@Nullable String homeNumber) {
        this.homeNumber = JsonNullable.of(homeNumber);
        return this;
    }


    /**
     * Apartment (unit) number.
     */
    public RecipientInline withFlatNumber(@Nullable String flatNumber) {
        this.flatNumber = JsonNullable.of(flatNumber);
        return this;
    }


    /**
     * Postal code. For `PL`, 5-digit values are normalized to the `NN-NNN` format.
     */
    public RecipientInline withPostCode(@Nullable String postCode) {
        this.postCode = JsonNullable.of(postCode);
        return this;
    }


    /**
     * City.
     */
    public RecipientInline withCity(@Nullable String city) {
        this.city = JsonNullable.of(city);
        return this;
    }


    /**
     * Country code in ISO 3166-1 alpha-2 format. Default: "PL". Value is automatically uppercased.
     * 
     * <p>Full list: https://www.iso.org/iso-3166-country-codes.html
     */
    public RecipientInline withCountry(@Nullable String country) {
        this.country = JsonNullable.of(country);
        return this;
    }


    /**
     * Phone number (E.164 format recommended).
     */
    public RecipientInline withPhoneNumber(@Nullable String phoneNumber) {
        this.phoneNumber = JsonNullable.of(phoneNumber);
        return this;
    }


    /**
     * Optional postscript printed above the recipient data on the envelope.
     */
    public RecipientInline withPostscript(@Nullable String postscript) {
        this.postscript = JsonNullable.of(postscript);
        return this;
    }


    /**
     * Custom shipment identifier assigned by the user.
     */
    public RecipientInline withCustomId(@Nullable String customId) {
        this.customId = JsonNullable.of(customId);
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RecipientInline other = (RecipientInline) o;
        return 
            Utils.enhancedDeepEquals(this.name, other.name) &&
            Utils.enhancedDeepEquals(this.name2, other.name2) &&
            Utils.enhancedDeepEquals(this.address, other.address) &&
            Utils.enhancedDeepEquals(this.homeNumber, other.homeNumber) &&
            Utils.enhancedDeepEquals(this.flatNumber, other.flatNumber) &&
            Utils.enhancedDeepEquals(this.postCode, other.postCode) &&
            Utils.enhancedDeepEquals(this.city, other.city) &&
            Utils.enhancedDeepEquals(this.country, other.country) &&
            Utils.enhancedDeepEquals(this.phoneNumber, other.phoneNumber) &&
            Utils.enhancedDeepEquals(this.postscript, other.postscript) &&
            Utils.enhancedDeepEquals(this.customId, other.customId);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            name, name2, address,
            homeNumber, flatNumber, postCode,
            city, country, phoneNumber,
            postscript, customId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(RecipientInline.class,
                "name", name,
                "name2", name2,
                "address", address,
                "homeNumber", homeNumber,
                "flatNumber", flatNumber,
                "postCode", postCode,
                "city", city,
                "country", country,
                "phoneNumber", phoneNumber,
                "postscript", postscript,
                "customId", customId);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String name;

        private JsonNullable<String> name2;

        private String address;

        private JsonNullable<String> homeNumber;

        private JsonNullable<String> flatNumber;

        private String postCode;

        private String city;

        private JsonNullable<String> country;

        private JsonNullable<String> phoneNumber;

        private JsonNullable<String> postscript;

        private JsonNullable<String> customId;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Name (person or company) — line 1.
         */
        public Builder name(@Nullable String name) {
            this.name = name;
            return this;
        }

        /**
         * Name (person or company) — line 2.
         */
        public Builder name2(@Nullable String name2) {
            this.name2 = JsonNullable.of(name2);
            return this;
        }

        /**
         * Street address.
         */
        public Builder address(@Nullable String address) {
            this.address = address;
            return this;
        }

        /**
         * Building number.
         */
        public Builder homeNumber(@Nullable String homeNumber) {
            this.homeNumber = JsonNullable.of(homeNumber);
            return this;
        }

        /**
         * Apartment (unit) number.
         */
        public Builder flatNumber(@Nullable String flatNumber) {
            this.flatNumber = JsonNullable.of(flatNumber);
            return this;
        }

        /**
         * Postal code. For `PL`, 5-digit values are normalized to the `NN-NNN` format.
         */
        public Builder postCode(@Nullable String postCode) {
            this.postCode = postCode;
            return this;
        }

        /**
         * City.
         */
        public Builder city(@Nullable String city) {
            this.city = city;
            return this;
        }

        /**
         * Country code in ISO 3166-1 alpha-2 format. Default: "PL". Value is automatically uppercased.
         * 
         * <p>Full list: https://www.iso.org/iso-3166-country-codes.html
         */
        public Builder country(@Nullable String country) {
            this.country = JsonNullable.of(country);
            return this;
        }

        /**
         * Phone number (E.164 format recommended).
         */
        public Builder phoneNumber(@Nullable String phoneNumber) {
            this.phoneNumber = JsonNullable.of(phoneNumber);
            return this;
        }

        /**
         * Optional postscript printed above the recipient data on the envelope.
         */
        public Builder postscript(@Nullable String postscript) {
            this.postscript = JsonNullable.of(postscript);
            return this;
        }

        /**
         * Custom shipment identifier assigned by the user.
         */
        public Builder customId(@Nullable String customId) {
            this.customId = JsonNullable.of(customId);
            return this;
        }

        public RecipientInline build() {
            return new RecipientInline(
                name, name2, address,
                homeNumber, flatNumber, postCode,
                city, country, phoneNumber,
                postscript, customId);
        }


        private static final LazySingletonValue<String> _SINGLETON_VALUE_Country =
                new LazySingletonValue<>(
                        "country",
                        "\"PL\"",
                        new TypeReference<String>() {});

        private static final LazySingletonValue<String> _SINGLETON_VALUE_CustomId =
                new LazySingletonValue<>(
                        "custom_id",
                        "null",
                        new TypeReference<String>() {});
    }
}
