/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package pl.postivo.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import pl.postivo.sdk.utils.OneOfDeserializer;
import pl.postivo.sdk.utils.TypedObject;
import pl.postivo.sdk.utils.Utils.JsonShape;
import pl.postivo.sdk.utils.Utils.TypeReferenceWithShape;
import pl.postivo.sdk.utils.Utils;

/**
 * Recipients
 * 
 * <p>A base recipient object.
 */
@JsonDeserialize(using = Recipients._Deserializer.class)
public class Recipients {

    @JsonValue
    private TypedObject value;
    
    private Recipients(TypedObject value) {
        this.value = value;
    }

    public static Recipients of(RecipientInline value) {
        Utils.checkNotNull(value, "value");
        return new Recipients(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<RecipientInline>(){}));
    }

    public static Recipients of(RecipientFromAddressBook value) {
        Utils.checkNotNull(value, "value");
        return new Recipients(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<RecipientFromAddressBook>(){}));
    }

    public static Recipients of(RecipientFromAddressBookByExternalId value) {
        Utils.checkNotNull(value, "value");
        return new Recipients(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<RecipientFromAddressBookByExternalId>(){}));
    }
    
    /**
     * Returns an instance of one of these types:
     * <ul>
     * <li>{@code pl.postivo.sdk.models.components.RecipientInline}</li>
     * <li>{@code pl.postivo.sdk.models.components.RecipientFromAddressBook}</li>
     * <li>{@code pl.postivo.sdk.models.components.RecipientFromAddressBookByExternalId}</li>
     * </ul>
     * 
     * <p>Use {@code instanceof} to determine what type is returned. For example:
     * 
     * <pre>
     * if (obj.value() instanceof String) {
     *     String answer = (String) obj.value();
     *     System.out.println("answer=" + answer);
     * }
     * </pre>
     * 
     * @return value of oneOf type
     **/ 
    public java.lang.Object value() {
        return value.value();
    }    
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Recipients other = (Recipients) o;
        return Utils.enhancedDeepEquals(this.value.value(), other.value.value()); 
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(value.value());
    }
    
    @SuppressWarnings("serial")
    public static final class _Deserializer extends OneOfDeserializer<Recipients> {

        public _Deserializer() {
            super(Recipients.class, false,
                  TypeReferenceWithShape.of(new TypeReference<RecipientInline>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<RecipientFromAddressBookByExternalId>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<RecipientFromAddressBook>() {}, JsonShape.DEFAULT));
        }
    }
    
    @Override
    public String toString() {
        return Utils.toString(Recipients.class,
                "value", value);
    }
 
}

