/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package pl.postivo.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;
import pl.postivo.sdk.utils.LazySingletonValue;
import pl.postivo.sdk.utils.Utils;

/**
 * RecipientFromAddressBook
 * 
 * <p>Select recipient data for a shipment from the Address Book.
 */
public class RecipientFromAddressBook {
    /**
     * Global ID of the recipient stored in the personal Address Book.
     */
    @JsonProperty("id")
    private long id;

    /**
     * User-assigned custom shipment ID.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("custom_id")
    private JsonNullable<String> customId;

    /**
     * Optional postscript printed above the recipient data on the envelope.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("postscript")
    private JsonNullable<String> postscript;

    @JsonCreator
    public RecipientFromAddressBook(
            @JsonProperty("id") long id,
            @JsonProperty("custom_id") @Nullable JsonNullable<String> customId,
            @JsonProperty("postscript") @Nullable JsonNullable<String> postscript) {
        this.id = id;
        this.customId = Optional.ofNullable(customId)
            .orElse(JsonNullable.of(Builder._SINGLETON_VALUE_CustomId.value()));
        this.postscript = Optional.ofNullable(postscript)
            .orElse(JsonNullable.undefined());
    }
    
    public RecipientFromAddressBook(
            long id) {
        this(id, null, null);
    }

    /**
     * Global ID of the recipient stored in the personal Address Book.
     */
    public long id() {
        return this.id;
    }

    /**
     * User-assigned custom shipment ID.
     */
    public JsonNullable<String> customId() {
        return this.customId;
    }

    /**
     * Optional postscript printed above the recipient data on the envelope.
     */
    public JsonNullable<String> postscript() {
        return this.postscript;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Global ID of the recipient stored in the personal Address Book.
     */
    public RecipientFromAddressBook withId(long id) {
        this.id = id;
        return this;
    }


    /**
     * User-assigned custom shipment ID.
     */
    public RecipientFromAddressBook withCustomId(@Nullable String customId) {
        this.customId = JsonNullable.of(customId);
        return this;
    }


    /**
     * Optional postscript printed above the recipient data on the envelope.
     */
    public RecipientFromAddressBook withPostscript(@Nullable String postscript) {
        this.postscript = JsonNullable.of(postscript);
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RecipientFromAddressBook other = (RecipientFromAddressBook) o;
        return 
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.customId, other.customId) &&
            Utils.enhancedDeepEquals(this.postscript, other.postscript);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            id, customId, postscript);
    }
    
    @Override
    public String toString() {
        return Utils.toString(RecipientFromAddressBook.class,
                "id", id,
                "customId", customId,
                "postscript", postscript);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private long id;

        private JsonNullable<String> customId;

        private JsonNullable<String> postscript;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Global ID of the recipient stored in the personal Address Book.
         */
        public Builder id(long id) {
            this.id = id;
            return this;
        }

        /**
         * User-assigned custom shipment ID.
         */
        public Builder customId(@Nullable String customId) {
            this.customId = JsonNullable.of(customId);
            return this;
        }

        /**
         * Optional postscript printed above the recipient data on the envelope.
         */
        public Builder postscript(@Nullable String postscript) {
            this.postscript = JsonNullable.of(postscript);
            return this;
        }

        public RecipientFromAddressBook build() {
            return new RecipientFromAddressBook(
                id, customId, postscript);
        }


        private static final LazySingletonValue<String> _SINGLETON_VALUE_CustomId =
                new LazySingletonValue<>(
                        "custom_id",
                        "null",
                        new TypeReference<String>() {});
    }
}
