/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package pl.postivo.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import pl.postivo.sdk.utils.HasSecurity;
import pl.postivo.sdk.utils.SpeakeasyMetadata;
import pl.postivo.sdk.utils.Utils;


public class Security implements HasSecurity {

    @SpeakeasyMetadata("security:scheme=true,type=http,subtype=bearer,name=Authorization")
    private String bearer;

    @JsonCreator
    public Security(
            @Nullable String bearer) {
        this.bearer = bearer;
    }
    
    public Security() {
        this(null);
    }

    public Optional<String> bearer() {
        return Optional.ofNullable(this.bearer);
    }

    public static Builder builder() {
        return new Builder();
    }


    public Security withBearer(@Nullable String bearer) {
        this.bearer = bearer;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Security other = (Security) o;
        return 
            Utils.enhancedDeepEquals(this.bearer, other.bearer);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            bearer);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Security.class,
                "bearer", bearer);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String bearer;

        private Builder() {
          // force use of static builder() method
        }

        public Builder bearer(@Nullable String bearer) {
            this.bearer = bearer;
            return this;
        }

        public Security build() {
            return new Security(
                bearer);
        }

    }
}
