/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package pl.postivo.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;
import pl.postivo.sdk.utils.Utils;

/**
 * Sender
 * 
 * <p>Sender data for the shipment.
 */
public class Sender {
    /**
     * Sender name (person or company) — line 1.
     */
    @JsonInclude(Include.ALWAYS)
    @JsonProperty("name")
    private JsonNullable<String> name;

    /**
     * Sender name (person or company) — line 2.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name2")
    private JsonNullable<String> name2;

    /**
     * Street address of the sender.
     */
    @JsonInclude(Include.ALWAYS)
    @JsonProperty("address")
    private JsonNullable<String> address;

    /**
     * Building number of the sender.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("home_number")
    private JsonNullable<String> homeNumber;

    /**
     * Apartment (unit) number of the sender.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("flat_number")
    private JsonNullable<String> flatNumber;

    /**
     * Postal code. For `PL`, 5-digit values are normalized to the `NN-NNN` format.
     */
    @JsonInclude(Include.ALWAYS)
    @JsonProperty("post_code")
    private JsonNullable<String> postCode;

    /**
     * City of the sender.
     */
    @JsonInclude(Include.ALWAYS)
    @JsonProperty("city")
    private JsonNullable<String> city;

    /**
     * Country code in ISO 3166-1 alpha-2 format. Value is automatically uppercased. Full list:
     * https://www.iso.org/iso-3166-country-codes.html
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("country")
    private JsonNullable<String> country;

    @JsonCreator
    public Sender(
            @JsonProperty("name") @Nullable String name,
            @JsonProperty("name2") @Nullable JsonNullable<String> name2,
            @JsonProperty("address") @Nullable String address,
            @JsonProperty("home_number") @Nullable JsonNullable<String> homeNumber,
            @JsonProperty("flat_number") @Nullable JsonNullable<String> flatNumber,
            @JsonProperty("post_code") @Nullable String postCode,
            @JsonProperty("city") @Nullable String city,
            @JsonProperty("country") @Nullable JsonNullable<String> country) {
        this.name = JsonNullable.of(name);
        this.name2 = Optional.ofNullable(name2)
            .orElse(JsonNullable.undefined());
        this.address = JsonNullable.of(address);
        this.homeNumber = Optional.ofNullable(homeNumber)
            .orElse(JsonNullable.undefined());
        this.flatNumber = Optional.ofNullable(flatNumber)
            .orElse(JsonNullable.undefined());
        this.postCode = JsonNullable.of(postCode);
        this.city = JsonNullable.of(city);
        this.country = Optional.ofNullable(country)
            .orElse(JsonNullable.undefined());
    }
    
    public Sender() {
        this(null, null, null,
            null, null, null,
            null, null);
    }

    /**
     * Sender name (person or company) — line 1.
     */
    public JsonNullable<String> name() {
        return this.name;
    }

    /**
     * Sender name (person or company) — line 2.
     */
    public JsonNullable<String> name2() {
        return this.name2;
    }

    /**
     * Street address of the sender.
     */
    public JsonNullable<String> address() {
        return this.address;
    }

    /**
     * Building number of the sender.
     */
    public JsonNullable<String> homeNumber() {
        return this.homeNumber;
    }

    /**
     * Apartment (unit) number of the sender.
     */
    public JsonNullable<String> flatNumber() {
        return this.flatNumber;
    }

    /**
     * Postal code. For `PL`, 5-digit values are normalized to the `NN-NNN` format.
     */
    public JsonNullable<String> postCode() {
        return this.postCode;
    }

    /**
     * City of the sender.
     */
    public JsonNullable<String> city() {
        return this.city;
    }

    /**
     * Country code in ISO 3166-1 alpha-2 format. Value is automatically uppercased. Full list:
     * https://www.iso.org/iso-3166-country-codes.html
     */
    public JsonNullable<String> country() {
        return this.country;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Sender name (person or company) — line 1.
     */
    public Sender withName(@Nullable String name) {
        this.name = JsonNullable.of(name);
        return this;
    }


    /**
     * Sender name (person or company) — line 2.
     */
    public Sender withName2(@Nullable String name2) {
        this.name2 = JsonNullable.of(name2);
        return this;
    }


    /**
     * Street address of the sender.
     */
    public Sender withAddress(@Nullable String address) {
        this.address = JsonNullable.of(address);
        return this;
    }


    /**
     * Building number of the sender.
     */
    public Sender withHomeNumber(@Nullable String homeNumber) {
        this.homeNumber = JsonNullable.of(homeNumber);
        return this;
    }


    /**
     * Apartment (unit) number of the sender.
     */
    public Sender withFlatNumber(@Nullable String flatNumber) {
        this.flatNumber = JsonNullable.of(flatNumber);
        return this;
    }


    /**
     * Postal code. For `PL`, 5-digit values are normalized to the `NN-NNN` format.
     */
    public Sender withPostCode(@Nullable String postCode) {
        this.postCode = JsonNullable.of(postCode);
        return this;
    }


    /**
     * City of the sender.
     */
    public Sender withCity(@Nullable String city) {
        this.city = JsonNullable.of(city);
        return this;
    }


    /**
     * Country code in ISO 3166-1 alpha-2 format. Value is automatically uppercased. Full list:
     * https://www.iso.org/iso-3166-country-codes.html
     */
    public Sender withCountry(@Nullable String country) {
        this.country = JsonNullable.of(country);
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Sender other = (Sender) o;
        return 
            Utils.enhancedDeepEquals(this.name, other.name) &&
            Utils.enhancedDeepEquals(this.name2, other.name2) &&
            Utils.enhancedDeepEquals(this.address, other.address) &&
            Utils.enhancedDeepEquals(this.homeNumber, other.homeNumber) &&
            Utils.enhancedDeepEquals(this.flatNumber, other.flatNumber) &&
            Utils.enhancedDeepEquals(this.postCode, other.postCode) &&
            Utils.enhancedDeepEquals(this.city, other.city) &&
            Utils.enhancedDeepEquals(this.country, other.country);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            name, name2, address,
            homeNumber, flatNumber, postCode,
            city, country);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Sender.class,
                "name", name,
                "name2", name2,
                "address", address,
                "homeNumber", homeNumber,
                "flatNumber", flatNumber,
                "postCode", postCode,
                "city", city,
                "country", country);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String name;

        private JsonNullable<String> name2;

        private String address;

        private JsonNullable<String> homeNumber;

        private JsonNullable<String> flatNumber;

        private String postCode;

        private String city;

        private JsonNullable<String> country;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Sender name (person or company) — line 1.
         */
        public Builder name(@Nullable String name) {
            this.name = name;
            return this;
        }

        /**
         * Sender name (person or company) — line 2.
         */
        public Builder name2(@Nullable String name2) {
            this.name2 = JsonNullable.of(name2);
            return this;
        }

        /**
         * Street address of the sender.
         */
        public Builder address(@Nullable String address) {
            this.address = address;
            return this;
        }

        /**
         * Building number of the sender.
         */
        public Builder homeNumber(@Nullable String homeNumber) {
            this.homeNumber = JsonNullable.of(homeNumber);
            return this;
        }

        /**
         * Apartment (unit) number of the sender.
         */
        public Builder flatNumber(@Nullable String flatNumber) {
            this.flatNumber = JsonNullable.of(flatNumber);
            return this;
        }

        /**
         * Postal code. For `PL`, 5-digit values are normalized to the `NN-NNN` format.
         */
        public Builder postCode(@Nullable String postCode) {
            this.postCode = postCode;
            return this;
        }

        /**
         * City of the sender.
         */
        public Builder city(@Nullable String city) {
            this.city = city;
            return this;
        }

        /**
         * Country code in ISO 3166-1 alpha-2 format. Value is automatically uppercased. Full list:
         * https://www.iso.org/iso-3166-country-codes.html
         */
        public Builder country(@Nullable String country) {
            this.country = JsonNullable.of(country);
            return this;
        }

        public Sender build() {
            return new Sender(
                name, name2, address,
                homeNumber, flatNumber, postCode,
                city, country);
        }

    }
}
