/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package pl.postivo.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import pl.postivo.sdk.utils.OneOfDeserializer;
import pl.postivo.sdk.utils.TypedObject;
import pl.postivo.sdk.utils.Utils.JsonShape;
import pl.postivo.sdk.utils.Utils.TypeReferenceWithShape;
import pl.postivo.sdk.utils.Utils;

/**
 * ShipmentDocuments
 * 
 * <p>Document payload to print and enclose into shipment. For a single document, provide `DocumentPdf`,
 * `DocumentLibrary`, or `DocumentMock` (for checking the price only). For multiple documents, provide
 * an array of `DocumentPdf`, `DocumentLibrary`, or `DocumentMock` objects (1–20).
 */
@JsonDeserialize(using = ShipmentDocuments._Deserializer.class)
public class ShipmentDocuments {

    @JsonValue
    private TypedObject value;
    
    private ShipmentDocuments(TypedObject value) {
        this.value = value;
    }

    public static ShipmentDocuments of(Documents value) {
        Utils.checkNotNull(value, "value");
        return new ShipmentDocuments(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<Documents>(){}));
    }

    public static ShipmentDocuments of(List<Documents> value) {
        Utils.checkNotNull(value, "value");
        return new ShipmentDocuments(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<List<Documents>>(){}));
    }
    
    /**
     * Returns an instance of one of these types:
     * <ul>
     * <li>{@code pl.postivo.sdk.models.components.Documents}</li>
     * <li>{@code java.util.List<pl.postivo.sdk.models.components.Documents>}</li>
     * </ul>
     * 
     * <p>Use {@code instanceof} to determine what type is returned. For example:
     * 
     * <pre>
     * if (obj.value() instanceof String) {
     *     String answer = (String) obj.value();
     *     System.out.println("answer=" + answer);
     * }
     * </pre>
     * 
     * @return value of oneOf type
     **/ 
    public java.lang.Object value() {
        return value.value();
    }    
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ShipmentDocuments other = (ShipmentDocuments) o;
        return Utils.enhancedDeepEquals(this.value.value(), other.value.value()); 
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(value.value());
    }
    
    @SuppressWarnings("serial")
    public static final class _Deserializer extends OneOfDeserializer<ShipmentDocuments> {

        public _Deserializer() {
            super(ShipmentDocuments.class, false,
                  TypeReferenceWithShape.of(new TypeReference<List<Documents>>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<Documents>() {}, JsonShape.DEFAULT));
        }
    }
    
    @Override
    public String toString() {
        return Utils.toString(ShipmentDocuments.class,
                "value", value);
    }
 
}

