/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package pl.postivo.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Boolean;
import java.lang.Override;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.Optional;
import pl.postivo.sdk.utils.Utils;

/**
 * ShipmentPriceStatus
 * 
 * <p>Shipment processing status.
 */
public class ShipmentPriceStatus {
    /**
     * Indicates whether an error occurred during processing.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("error")
    private Boolean error;

    /**
     * Status code.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("code")
    private String code;

    /**
     * Status description.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("description")
    private String description;

    /**
     * Status timestamp (UTC).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("date")
    private OffsetDateTime date;

    @JsonCreator
    public ShipmentPriceStatus(
            @JsonProperty("error") @Nullable Boolean error,
            @JsonProperty("code") @Nullable String code,
            @JsonProperty("description") @Nullable String description,
            @JsonProperty("date") @Nullable OffsetDateTime date) {
        this.error = error;
        this.code = code;
        this.description = description;
        this.date = date;
    }
    
    public ShipmentPriceStatus() {
        this(null, null, null,
            null);
    }

    /**
     * Indicates whether an error occurred during processing.
     */
    public Optional<Boolean> error() {
        return Optional.ofNullable(this.error);
    }

    /**
     * Status code.
     */
    public Optional<String> code() {
        return Optional.ofNullable(this.code);
    }

    /**
     * Status description.
     */
    public Optional<String> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * Status timestamp (UTC).
     */
    public Optional<OffsetDateTime> date() {
        return Optional.ofNullable(this.date);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Indicates whether an error occurred during processing.
     */
    public ShipmentPriceStatus withError(@Nullable Boolean error) {
        this.error = error;
        return this;
    }


    /**
     * Status code.
     */
    public ShipmentPriceStatus withCode(@Nullable String code) {
        this.code = code;
        return this;
    }


    /**
     * Status description.
     */
    public ShipmentPriceStatus withDescription(@Nullable String description) {
        this.description = description;
        return this;
    }


    /**
     * Status timestamp (UTC).
     */
    public ShipmentPriceStatus withDate(@Nullable OffsetDateTime date) {
        this.date = date;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ShipmentPriceStatus other = (ShipmentPriceStatus) o;
        return 
            Utils.enhancedDeepEquals(this.error, other.error) &&
            Utils.enhancedDeepEquals(this.code, other.code) &&
            Utils.enhancedDeepEquals(this.description, other.description) &&
            Utils.enhancedDeepEquals(this.date, other.date);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            error, code, description,
            date);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ShipmentPriceStatus.class,
                "error", error,
                "code", code,
                "description", description,
                "date", date);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Boolean error;

        private String code;

        private String description;

        private OffsetDateTime date;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Indicates whether an error occurred during processing.
         */
        public Builder error(@Nullable Boolean error) {
            this.error = error;
            return this;
        }

        /**
         * Status code.
         */
        public Builder code(@Nullable String code) {
            this.code = code;
            return this;
        }

        /**
         * Status description.
         */
        public Builder description(@Nullable String description) {
            this.description = description;
            return this;
        }

        /**
         * Status timestamp (UTC).
         */
        public Builder date(@Nullable OffsetDateTime date) {
            this.date = date;
            return this;
        }

        public ShipmentPriceStatus build() {
            return new ShipmentPriceStatus(
                error, code, description,
                date);
        }

    }
}
