/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package pl.postivo.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;
import pl.postivo.sdk.utils.Utils;

/**
 * ShipmentDetailsCarrier
 * 
 * <p>Postal operator handling the shipment.
 */
public class ShipmentDetailsCarrier {
    /**
     * Postal operator ID.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    private JsonNullable<Long> id;

    /**
     * Postal operator name.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    private JsonNullable<String> name;

    @JsonCreator
    public ShipmentDetailsCarrier(
            @JsonProperty("id") @Nullable JsonNullable<Long> id,
            @JsonProperty("name") @Nullable JsonNullable<String> name) {
        this.id = Optional.ofNullable(id)
            .orElse(JsonNullable.undefined());
        this.name = Optional.ofNullable(name)
            .orElse(JsonNullable.undefined());
    }
    
    public ShipmentDetailsCarrier() {
        this(null, null);
    }

    /**
     * Postal operator ID.
     */
    public JsonNullable<Long> id() {
        return this.id;
    }

    /**
     * Postal operator name.
     */
    public JsonNullable<String> name() {
        return this.name;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Postal operator ID.
     */
    public ShipmentDetailsCarrier withId(@Nullable Long id) {
        this.id = JsonNullable.of(id);
        return this;
    }


    /**
     * Postal operator name.
     */
    public ShipmentDetailsCarrier withName(@Nullable String name) {
        this.name = JsonNullable.of(name);
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ShipmentDetailsCarrier other = (ShipmentDetailsCarrier) o;
        return 
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.name, other.name);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            id, name);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ShipmentDetailsCarrier.class,
                "id", id,
                "name", name);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private JsonNullable<Long> id;

        private JsonNullable<String> name;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Postal operator ID.
         */
        public Builder id(@Nullable Long id) {
            this.id = JsonNullable.of(id);
            return this;
        }

        /**
         * Postal operator name.
         */
        public Builder name(@Nullable String name) {
            this.name = JsonNullable.of(name);
            return this;
        }

        public ShipmentDetailsCarrier build() {
            return new ShipmentDetailsCarrier(
                id, name);
        }

    }
}
