/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package pl.postivo.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import pl.postivo.sdk.utils.Utils;


public class StatusCode {
    /**
     * Unique status code.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("code")
    private String code;

    /**
     * Status name.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    private String name;

    /**
     * Status description.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("description")
    private String description;

    @JsonCreator
    public StatusCode(
            @JsonProperty("code") @Nullable String code,
            @JsonProperty("name") @Nullable String name,
            @JsonProperty("description") @Nullable String description) {
        this.code = code;
        this.name = name;
        this.description = description;
    }
    
    public StatusCode() {
        this(null, null, null);
    }

    /**
     * Unique status code.
     */
    public Optional<String> code() {
        return Optional.ofNullable(this.code);
    }

    /**
     * Status name.
     */
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * Status description.
     */
    public Optional<String> description() {
        return Optional.ofNullable(this.description);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Unique status code.
     */
    public StatusCode withCode(@Nullable String code) {
        this.code = code;
        return this;
    }


    /**
     * Status name.
     */
    public StatusCode withName(@Nullable String name) {
        this.name = name;
        return this;
    }


    /**
     * Status description.
     */
    public StatusCode withDescription(@Nullable String description) {
        this.description = description;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        StatusCode other = (StatusCode) o;
        return 
            Utils.enhancedDeepEquals(this.code, other.code) &&
            Utils.enhancedDeepEquals(this.name, other.name) &&
            Utils.enhancedDeepEquals(this.description, other.description);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            code, name, description);
    }
    
    @Override
    public String toString() {
        return Utils.toString(StatusCode.class,
                "code", code,
                "name", name,
                "description", description);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String code;

        private String name;

        private String description;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Unique status code.
         */
        public Builder code(@Nullable String code) {
            this.code = code;
            return this;
        }

        /**
         * Status name.
         */
        public Builder name(@Nullable String name) {
            this.name = name;
            return this;
        }

        /**
         * Status description.
         */
        public Builder description(@Nullable String description) {
            this.description = description;
            return this;
        }

        public StatusCode build() {
            return new StatusCode(
                code, name, description);
        }

    }
}
