/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package pl.postivo.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import java.lang.Override;
import java.lang.String;
import pl.postivo.sdk.utils.SpeakeasyMetadata;
import pl.postivo.sdk.utils.Utils;


public class AddContactToGroupRequest {
    /**
     * Global contact <code>id</code> to add to the group.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")
    private long id;

    /**
     * Group <code>id</code> to associate with the contact.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=group_id")
    private long groupId;

    @JsonCreator
    public AddContactToGroupRequest(
            long id,
            long groupId) {
        this.id = id;
        this.groupId = groupId;
    }

    /**
     * Global contact <code>id</code> to add to the group.
     */
    public long id() {
        return this.id;
    }

    /**
     * Group <code>id</code> to associate with the contact.
     */
    public long groupId() {
        return this.groupId;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Global contact <code>id</code> to add to the group.
     */
    public AddContactToGroupRequest withId(long id) {
        this.id = id;
        return this;
    }


    /**
     * Group <code>id</code> to associate with the contact.
     */
    public AddContactToGroupRequest withGroupId(long groupId) {
        this.groupId = groupId;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AddContactToGroupRequest other = (AddContactToGroupRequest) o;
        return 
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.groupId, other.groupId);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            id, groupId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(AddContactToGroupRequest.class,
                "id", id,
                "groupId", groupId);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private long id;

        private long groupId;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Global contact <code>id</code> to add to the group.
         */
        public Builder id(long id) {
            this.id = id;
            return this;
        }

        /**
         * Group <code>id</code> to associate with the contact.
         */
        public Builder groupId(long groupId) {
            this.groupId = groupId;
            return this;
        }

        public AddContactToGroupRequest build() {
            return new AddContactToGroupRequest(
                id, groupId);
        }

    }
}
