/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package pl.postivo.sdk.models.operations;

import static pl.postivo.sdk.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Exception;
import java.lang.String;
import pl.postivo.sdk.SDKConfiguration;
import pl.postivo.sdk.operations.AddContactByExtIdToGroup;
import pl.postivo.sdk.utils.Headers;
import pl.postivo.sdk.utils.Options;
import pl.postivo.sdk.utils.RetryConfig;
import pl.postivo.sdk.utils.Utils;

public class AddContactByExtIdToGroupRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final AddContactByExtIdToGroupRequest.Builder pojoBuilder;
    private AddContactByExtIdToGroupRequest request;
    private final Options.Builder optionsBuilder;
    private boolean _setterCalled;

    public AddContactByExtIdToGroupRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = AddContactByExtIdToGroupRequest.builder();
        this.optionsBuilder = Options.builder();
    }

    public AddContactByExtIdToGroupRequestBuilder extId(@Nonnull String extId) {
        this.pojoBuilder.extId(extId);
        this._setterCalled = true;
        return this;
    }

    public AddContactByExtIdToGroupRequestBuilder groupId(long groupId) {
        this.pojoBuilder.groupId(groupId);
        this._setterCalled = true;
        return this;
    }

    public AddContactByExtIdToGroupRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    private AddContactByExtIdToGroupRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public AddContactByExtIdToGroupRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public AddContactByExtIdToGroupResponse call() throws Exception {
        Options options = optionsBuilder.build();
        RequestOperation<AddContactByExtIdToGroupRequest, AddContactByExtIdToGroupResponse> operation
              = new AddContactByExtIdToGroup.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
