/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package pl.postivo.sdk.models.operations;

import static pl.postivo.sdk.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Exception;
import pl.postivo.sdk.SDKConfiguration;
import pl.postivo.sdk.models.components.Sender;
import pl.postivo.sdk.operations.AddSender;
import pl.postivo.sdk.utils.Headers;
import pl.postivo.sdk.utils.Options;
import pl.postivo.sdk.utils.RetryConfig;
import pl.postivo.sdk.utils.Utils;

public class AddSenderRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private Sender request;
    private final Options.Builder optionsBuilder;

    public AddSenderRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.optionsBuilder = Options.builder();
    }

    public AddSenderRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    public AddSenderRequestBuilder request(@Nonnull Sender request) {
        this.request = Utils.checkNotNull(request, "request");
        return this;
    }

    private Sender _buildRequest() {
        return this.request;
    }
    
    public AddSenderRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public AddSenderResponse call() throws Exception {
        Options options = optionsBuilder.build();
        RequestOperation<Sender, AddSenderResponse> operation
              = new AddSender.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
