/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package pl.postivo.sdk.models.operations;

import static pl.postivo.sdk.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Exception;
import java.lang.String;
import java.util.List;
import pl.postivo.sdk.SDKConfiguration;
import pl.postivo.sdk.operations.CancelShipment;
import pl.postivo.sdk.utils.Headers;
import pl.postivo.sdk.utils.Options;
import pl.postivo.sdk.utils.RetryConfig;
import pl.postivo.sdk.utils.Utils;

public class CancelShipmentRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final CancelShipmentRequest.Builder pojoBuilder;
    private CancelShipmentRequest request;
    private final Options.Builder optionsBuilder;
    private boolean _setterCalled;

    public CancelShipmentRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = CancelShipmentRequest.builder();
        this.optionsBuilder = Options.builder();
    }

    public CancelShipmentRequestBuilder ids(@Nonnull List<String> ids) {
        this.pojoBuilder.ids(ids);
        this._setterCalled = true;
        return this;
    }

    public CancelShipmentRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    private CancelShipmentRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public CancelShipmentRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CancelShipmentResponse call() throws Exception {
        Options options = optionsBuilder.build();
        RequestOperation<CancelShipmentRequest, CancelShipmentResponse> operation
              = new CancelShipment.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
