/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package pl.postivo.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * ContactHandling
 * 
 * <p>How to handle contacts that belong to the group.
 */
public enum ContactHandling {
    /**
     * Detach contacts from the removed group; keep them in the Address Book.
     */
    DETACH("detach"),
    /**
     * Delete the group and also remove contacts that belong only to this group.
     */
    DELETE("delete");

    @JsonValue
    private final String value;

    ContactHandling(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<ContactHandling> fromValue(String value) {
        for (ContactHandling o: ContactHandling.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

