/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package pl.postivo.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import java.lang.Override;
import java.lang.String;
import pl.postivo.sdk.utils.SpeakeasyMetadata;
import pl.postivo.sdk.utils.Utils;


public class DeleteContactRequest {
    /**
     * Global contact <code>id</code> to remove.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")
    private long id;

    @JsonCreator
    public DeleteContactRequest(
            long id) {
        this.id = id;
    }

    /**
     * Global contact <code>id</code> to remove.
     */
    public long id() {
        return this.id;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Global contact <code>id</code> to remove.
     */
    public DeleteContactRequest withId(long id) {
        this.id = id;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DeleteContactRequest other = (DeleteContactRequest) o;
        return 
            Utils.enhancedDeepEquals(this.id, other.id);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            id);
    }
    
    @Override
    public String toString() {
        return Utils.toString(DeleteContactRequest.class,
                "id", id);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private long id;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Global contact <code>id</code> to remove.
         */
        public Builder id(long id) {
            this.id = id;
            return this;
        }

        public DeleteContactRequest build() {
            return new DeleteContactRequest(
                id);
        }

    }
}
