/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package pl.postivo.sdk.models.operations;

import static pl.postivo.sdk.operations.Operations.RequestOperation;

import jakarta.annotation.Nullable;
import java.lang.Exception;
import pl.postivo.sdk.SDKConfiguration;
import pl.postivo.sdk.operations.DeleteGroup;
import pl.postivo.sdk.utils.Headers;
import pl.postivo.sdk.utils.Options;
import pl.postivo.sdk.utils.RetryConfig;
import pl.postivo.sdk.utils.Utils;

public class DeleteGroupRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final DeleteGroupRequest.Builder pojoBuilder;
    private DeleteGroupRequest request;
    private final Options.Builder optionsBuilder;
    private boolean _setterCalled;

    public DeleteGroupRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = DeleteGroupRequest.builder();
        this.optionsBuilder = Options.builder();
    }

    public DeleteGroupRequestBuilder id(long id) {
        this.pojoBuilder.id(id);
        this._setterCalled = true;
        return this;
    }

    public DeleteGroupRequestBuilder contacts(@Nullable ContactHandling contacts) {
        this.pojoBuilder.contacts(contacts);
        this._setterCalled = true;
        return this;
    }

    public DeleteGroupRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    private DeleteGroupRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public DeleteGroupRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public DeleteGroupResponse call() throws Exception {
        Options options = optionsBuilder.build();
        RequestOperation<DeleteGroupRequest, DeleteGroupResponse> operation
              = new DeleteGroup.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
