/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package pl.postivo.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * DocumentType
 * 
 * <p>Type of document/certificate to generate.
 */
public enum DocumentType {
    /**
     * Dispatch confirmation certificate
     */
    DISPATCH_CERT("dispatch_cert"),
    /**
     * Envelope template preview
     */
    ENVELOPE("envelope"),
    /**
     * EPO certificate in PDF format (Elektroniczne Potwierdzenie Odbioru)
     */
    EPO_PDF("epo_pdf"),
    /**
     * EPO certificate in XML format (Elektroniczne Potwierdzenie Odbioru)
     */
    EPO_XML("epo_xml");

    @JsonValue
    private final String value;

    DocumentType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<DocumentType> fromValue(String value) {
        for (DocumentType o: DocumentType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

