/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package pl.postivo.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import pl.postivo.sdk.utils.SpeakeasyMetadata;
import pl.postivo.sdk.utils.Utils;


public class GetContactByExternalIdRequest {
    /**
     * External (custom) ID of the contact to fetch.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=ext_id")
    private String extId;

    @JsonCreator
    public GetContactByExternalIdRequest(
            @Nonnull String extId) {
        this.extId = Optional.ofNullable(extId)
            .orElseThrow(() -> new IllegalArgumentException("extId cannot be null"));
    }

    /**
     * External (custom) ID of the contact to fetch.
     */
    public String extId() {
        return this.extId;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * External (custom) ID of the contact to fetch.
     */
    public GetContactByExternalIdRequest withExtId(@Nonnull String extId) {
        this.extId = Utils.checkNotNull(extId, "extId");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetContactByExternalIdRequest other = (GetContactByExternalIdRequest) o;
        return 
            Utils.enhancedDeepEquals(this.extId, other.extId);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            extId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetContactByExternalIdRequest.class,
                "extId", extId);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String extId;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * External (custom) ID of the contact to fetch.
         */
        public Builder extId(@Nonnull String extId) {
            this.extId = Utils.checkNotNull(extId, "extId");
            return this;
        }

        public GetContactByExternalIdRequest build() {
            return new GetContactByExternalIdRequest(
                extId);
        }

    }
}
