/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package pl.postivo.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.io.InputStream;
import java.lang.Override;
import java.lang.String;
import java.net.http.HttpResponse;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;
import pl.postivo.sdk.models.components.ContactResponse;
import pl.postivo.sdk.models.components.ErrorResponse;
import pl.postivo.sdk.utils.Response;
import pl.postivo.sdk.utils.Utils;


public class GetContactByExternalIdResponse implements Response {
    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * The request was processed successfully. Contact details are included in the response body.
     */
    private ContactResponse contactResponse;

    /**
     * Invalid request.
     */
    private JsonNullable<ErrorResponse> errorResponse;

    @JsonCreator
    public GetContactByExternalIdResponse(
            @Nonnull String contentType,
            int statusCode,
            @Nonnull HttpResponse<InputStream> rawResponse,
            @Nullable ContactResponse contactResponse,
            @Nullable JsonNullable<ErrorResponse> errorResponse) {
        this.contentType = Optional.ofNullable(contentType)
            .orElseThrow(() -> new IllegalArgumentException("contentType cannot be null"));
        this.statusCode = statusCode;
        this.rawResponse = Optional.ofNullable(rawResponse)
            .orElseThrow(() -> new IllegalArgumentException("rawResponse cannot be null"));
        this.contactResponse = contactResponse;
        this.errorResponse = Optional.ofNullable(errorResponse)
            .orElse(JsonNullable.undefined());
    }
    
    public GetContactByExternalIdResponse(
            @Nonnull String contentType,
            int statusCode,
            @Nonnull HttpResponse<InputStream> rawResponse) {
        this(contentType, statusCode, rawResponse,
            null, null);
    }

    /**
     * HTTP response content type for this operation
     */
    public String contentType() {
        return this.contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    public int statusCode() {
        return this.statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public HttpResponse<InputStream> rawResponse() {
        return this.rawResponse;
    }

    /**
     * The request was processed successfully. Contact details are included in the response body.
     */
    public Optional<ContactResponse> contactResponse() {
        return Optional.ofNullable(this.contactResponse);
    }

    /**
     * Invalid request.
     */
    public JsonNullable<ErrorResponse> errorResponse() {
        return this.errorResponse;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * HTTP response content type for this operation
     */
    public GetContactByExternalIdResponse withContentType(@Nonnull String contentType) {
        this.contentType = Utils.checkNotNull(contentType, "contentType");
        return this;
    }


    /**
     * HTTP response status code for this operation
     */
    public GetContactByExternalIdResponse withStatusCode(int statusCode) {
        this.statusCode = statusCode;
        return this;
    }


    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public GetContactByExternalIdResponse withRawResponse(@Nonnull HttpResponse<InputStream> rawResponse) {
        this.rawResponse = Utils.checkNotNull(rawResponse, "rawResponse");
        return this;
    }


    /**
     * The request was processed successfully. Contact details are included in the response body.
     */
    public GetContactByExternalIdResponse withContactResponse(@Nullable ContactResponse contactResponse) {
        this.contactResponse = contactResponse;
        return this;
    }


    /**
     * Invalid request.
     */
    public GetContactByExternalIdResponse withErrorResponse(@Nullable ErrorResponse errorResponse) {
        this.errorResponse = JsonNullable.of(errorResponse);
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetContactByExternalIdResponse other = (GetContactByExternalIdResponse) o;
        return 
            Utils.enhancedDeepEquals(this.contentType, other.contentType) &&
            Utils.enhancedDeepEquals(this.statusCode, other.statusCode) &&
            Utils.enhancedDeepEquals(this.rawResponse, other.rawResponse) &&
            Utils.enhancedDeepEquals(this.contactResponse, other.contactResponse) &&
            Utils.enhancedDeepEquals(this.errorResponse, other.errorResponse);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            contentType, statusCode, rawResponse,
            contactResponse, errorResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetContactByExternalIdResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "contactResponse", contactResponse,
                "errorResponse", errorResponse);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String contentType;

        private int statusCode;

        private HttpResponse<InputStream> rawResponse;

        private ContactResponse contactResponse;

        private JsonNullable<ErrorResponse> errorResponse;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(@Nonnull String contentType) {
            this.contentType = Utils.checkNotNull(contentType, "contentType");
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(@Nonnull HttpResponse<InputStream> rawResponse) {
            this.rawResponse = Utils.checkNotNull(rawResponse, "rawResponse");
            return this;
        }

        /**
         * The request was processed successfully. Contact details are included in the response body.
         */
        public Builder contactResponse(@Nullable ContactResponse contactResponse) {
            this.contactResponse = contactResponse;
            return this;
        }

        /**
         * Invalid request.
         */
        public Builder errorResponse(@Nullable ErrorResponse errorResponse) {
            this.errorResponse = JsonNullable.of(errorResponse);
            return this;
        }

        public GetContactByExternalIdResponse build() {
            return new GetContactByExternalIdResponse(
                contentType, statusCode, rawResponse,
                contactResponse, errorResponse);
        }

    }
}
