/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package pl.postivo.sdk.models.operations;

import static pl.postivo.sdk.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Exception;
import java.lang.String;
import pl.postivo.sdk.SDKConfiguration;
import pl.postivo.sdk.operations.GetSubaccountDetails;
import pl.postivo.sdk.utils.Headers;
import pl.postivo.sdk.utils.Options;
import pl.postivo.sdk.utils.RetryConfig;
import pl.postivo.sdk.utils.Utils;

public class GetSubaccountDetailsRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final GetSubaccountDetailsRequest.Builder pojoBuilder;
    private GetSubaccountDetailsRequest request;
    private final Options.Builder optionsBuilder;
    private boolean _setterCalled;

    public GetSubaccountDetailsRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = GetSubaccountDetailsRequest.builder();
        this.optionsBuilder = Options.builder();
    }

    public GetSubaccountDetailsRequestBuilder userLogin(@Nonnull String userLogin) {
        this.pojoBuilder.userLogin(userLogin);
        this._setterCalled = true;
        return this;
    }

    public GetSubaccountDetailsRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    private GetSubaccountDetailsRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public GetSubaccountDetailsRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public GetSubaccountDetailsResponse call() throws Exception {
        Options options = optionsBuilder.build();
        RequestOperation<GetSubaccountDetailsRequest, GetSubaccountDetailsResponse> operation
              = new GetSubaccountDetails.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
