/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package pl.postivo.sdk.models.operations;

import static pl.postivo.sdk.operations.Operations.RequestOperation;

import jakarta.annotation.Nullable;
import java.lang.Exception;
import pl.postivo.sdk.SDKConfiguration;
import pl.postivo.sdk.operations.RemoveContactFromGroup;
import pl.postivo.sdk.utils.Headers;
import pl.postivo.sdk.utils.Options;
import pl.postivo.sdk.utils.RetryConfig;
import pl.postivo.sdk.utils.Utils;

public class RemoveContactFromGroupRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final RemoveContactFromGroupRequest.Builder pojoBuilder;
    private RemoveContactFromGroupRequest request;
    private final Options.Builder optionsBuilder;
    private boolean _setterCalled;

    public RemoveContactFromGroupRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = RemoveContactFromGroupRequest.builder();
        this.optionsBuilder = Options.builder();
    }

    public RemoveContactFromGroupRequestBuilder id(long id) {
        this.pojoBuilder.id(id);
        this._setterCalled = true;
        return this;
    }

    public RemoveContactFromGroupRequestBuilder groupId(long groupId) {
        this.pojoBuilder.groupId(groupId);
        this._setterCalled = true;
        return this;
    }

    public RemoveContactFromGroupRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    private RemoveContactFromGroupRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public RemoveContactFromGroupRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public RemoveContactFromGroupResponse call() throws Exception {
        Options options = optionsBuilder.build();
        RequestOperation<RemoveContactFromGroupRequest, RemoveContactFromGroupResponse> operation
              = new RemoveContactFromGroup.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
