/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package pl.postivo.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import pl.postivo.sdk.models.components.Contact;
import pl.postivo.sdk.utils.SpeakeasyMetadata;
import pl.postivo.sdk.utils.Utils;


public class UpdateContactByExternalIdRequest {
    /**
     * External (custom) ID of the contact to update.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=ext_id")
    private String extId;

    /**
     * A <code>Contact</code> object with the updated fields.
     */
    @SpeakeasyMetadata("request:mediaType=application/json")
    private Contact contact;

    @JsonCreator
    public UpdateContactByExternalIdRequest(
            @Nonnull String extId,
            @Nonnull Contact contact) {
        this.extId = Optional.ofNullable(extId)
            .orElseThrow(() -> new IllegalArgumentException("extId cannot be null"));
        this.contact = Optional.ofNullable(contact)
            .orElseThrow(() -> new IllegalArgumentException("contact cannot be null"));
    }

    /**
     * External (custom) ID of the contact to update.
     */
    public String extId() {
        return this.extId;
    }

    /**
     * A <code>Contact</code> object with the updated fields.
     */
    public Contact contact() {
        return this.contact;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * External (custom) ID of the contact to update.
     */
    public UpdateContactByExternalIdRequest withExtId(@Nonnull String extId) {
        this.extId = Utils.checkNotNull(extId, "extId");
        return this;
    }


    /**
     * A <code>Contact</code> object with the updated fields.
     */
    public UpdateContactByExternalIdRequest withContact(@Nonnull Contact contact) {
        this.contact = Utils.checkNotNull(contact, "contact");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UpdateContactByExternalIdRequest other = (UpdateContactByExternalIdRequest) o;
        return 
            Utils.enhancedDeepEquals(this.extId, other.extId) &&
            Utils.enhancedDeepEquals(this.contact, other.contact);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            extId, contact);
    }
    
    @Override
    public String toString() {
        return Utils.toString(UpdateContactByExternalIdRequest.class,
                "extId", extId,
                "contact", contact);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String extId;

        private Contact contact;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * External (custom) ID of the contact to update.
         */
        public Builder extId(@Nonnull String extId) {
            this.extId = Utils.checkNotNull(extId, "extId");
            return this;
        }

        /**
         * A <code>Contact</code> object with the updated fields.
         */
        public Builder contact(@Nonnull Contact contact) {
            this.contact = Utils.checkNotNull(contact, "contact");
            return this;
        }

        public UpdateContactByExternalIdRequest build() {
            return new UpdateContactByExternalIdRequest(
                extId, contact);
        }

    }
}
