/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package pl.postivo.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import pl.postivo.sdk.models.components.Group;
import pl.postivo.sdk.utils.SpeakeasyMetadata;
import pl.postivo.sdk.utils.Utils;


public class UpdateGroupRequest {
    /**
     * Group `id` to update.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")
    private long id;

    /**
     * A `Group` object with the updated fields.
     */
    @SpeakeasyMetadata("request:mediaType=application/json")
    private Group group;

    @JsonCreator
    public UpdateGroupRequest(
            long id,
            @Nonnull Group group) {
        this.id = id;
        this.group = Optional.ofNullable(group)
            .orElseThrow(() -> new IllegalArgumentException("group cannot be null"));
    }

    /**
     * Group `id` to update.
     */
    public long id() {
        return this.id;
    }

    /**
     * A `Group` object with the updated fields.
     */
    public Group group() {
        return this.group;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Group `id` to update.
     */
    public UpdateGroupRequest withId(long id) {
        this.id = id;
        return this;
    }


    /**
     * A `Group` object with the updated fields.
     */
    public UpdateGroupRequest withGroup(@Nonnull Group group) {
        this.group = Utils.checkNotNull(group, "group");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UpdateGroupRequest other = (UpdateGroupRequest) o;
        return 
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.group, other.group);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            id, group);
    }
    
    @Override
    public String toString() {
        return Utils.toString(UpdateGroupRequest.class,
                "id", id,
                "group", group);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private long id;

        private Group group;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Group `id` to update.
         */
        public Builder id(long id) {
            this.id = id;
            return this;
        }

        /**
         * A `Group` object with the updated fields.
         */
        public Builder group(@Nonnull Group group) {
            this.group = Utils.checkNotNull(group, "group");
            return this;
        }

        public UpdateGroupRequest build() {
            return new UpdateGroupRequest(
                id, group);
        }

    }
}
