/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package pl.postivo.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import pl.postivo.sdk.utils.SpeakeasyMetadata;
import pl.postivo.sdk.utils.Utils;


public class VerifySenderRequest {
    /**
     * ID of the sender to verify.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")
    private long id;

    /**
     * Verification code received in the letter.
     */
    @SpeakeasyMetadata("request:mediaType=application/json")
    private VerifySenderRequestBody requestBody;

    @JsonCreator
    public VerifySenderRequest(
            long id,
            @Nonnull VerifySenderRequestBody requestBody) {
        this.id = id;
        this.requestBody = Optional.ofNullable(requestBody)
            .orElseThrow(() -> new IllegalArgumentException("requestBody cannot be null"));
    }

    /**
     * ID of the sender to verify.
     */
    public long id() {
        return this.id;
    }

    /**
     * Verification code received in the letter.
     */
    public VerifySenderRequestBody requestBody() {
        return this.requestBody;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * ID of the sender to verify.
     */
    public VerifySenderRequest withId(long id) {
        this.id = id;
        return this;
    }


    /**
     * Verification code received in the letter.
     */
    public VerifySenderRequest withRequestBody(@Nonnull VerifySenderRequestBody requestBody) {
        this.requestBody = Utils.checkNotNull(requestBody, "requestBody");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        VerifySenderRequest other = (VerifySenderRequest) o;
        return 
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.requestBody, other.requestBody);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            id, requestBody);
    }
    
    @Override
    public String toString() {
        return Utils.toString(VerifySenderRequest.class,
                "id", id,
                "requestBody", requestBody);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private long id;

        private VerifySenderRequestBody requestBody;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * ID of the sender to verify.
         */
        public Builder id(long id) {
            this.id = id;
            return this;
        }

        /**
         * Verification code received in the letter.
         */
        public Builder requestBody(@Nonnull VerifySenderRequestBody requestBody) {
            this.requestBody = Utils.checkNotNull(requestBody, "requestBody");
            return this;
        }

        public VerifySenderRequest build() {
            return new VerifySenderRequest(
                id, requestBody);
        }

    }
}
