/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package pl.postivo.sdk.models.operations.async;

import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.io.InputStream;
import java.lang.Override;
import java.lang.String;
import java.net.http.HttpResponse;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;
import pl.postivo.sdk.models.components.ErrorResponse;
import pl.postivo.sdk.models.components.ShipmentCancellation;
import pl.postivo.sdk.utils.AsyncResponse;
import pl.postivo.sdk.utils.Blob;
import pl.postivo.sdk.utils.Utils;


public class CancelShipmentResponse implements AsyncResponse {
    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<Blob> rawResponse;

    /**
     * The request was processed successfully. Check the shipment cancellation statuses in the response
     * body.
     */
    private List<ShipmentCancellation> shipmentCancellations;

    /**
     * Invalid request.
     */
    private JsonNullable<ErrorResponse> errorResponse;


    private Map<String, List<String>> headers;

    @JsonCreator
    public CancelShipmentResponse(
            @Nonnull String contentType,
            int statusCode,
            @Nonnull HttpResponse<Blob> rawResponse,
            @Nullable List<ShipmentCancellation> shipmentCancellations,
            @Nullable JsonNullable<ErrorResponse> errorResponse,
            @Nonnull Map<String, List<String>> headers) {
        headers = Utils.emptyMapIfNull(headers);
        this.contentType = Optional.ofNullable(contentType)
            .orElseThrow(() -> new IllegalArgumentException("contentType cannot be null"));
        this.statusCode = statusCode;
        this.rawResponse = Optional.ofNullable(rawResponse)
            .orElseThrow(() -> new IllegalArgumentException("rawResponse cannot be null"));
        this.shipmentCancellations = shipmentCancellations;
        this.errorResponse = Optional.ofNullable(errorResponse)
            .orElse(JsonNullable.undefined());
        this.headers = Optional.ofNullable(headers)
            .orElseThrow(() -> new IllegalArgumentException("headers cannot be null"));
    }
    
    public CancelShipmentResponse(
            @Nonnull String contentType,
            int statusCode,
            @Nonnull HttpResponse<Blob> rawResponse,
            @Nonnull Map<String, List<String>> headers) {
        this(contentType, statusCode, rawResponse,
            null, null, headers);
    }

    /**
     * HTTP response content type for this operation
     */
    public String contentType() {
        return this.contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    public int statusCode() {
        return this.statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public HttpResponse<Blob> rawResponse() {
        return this.rawResponse;
    }

    /**
     * The request was processed successfully. Check the shipment cancellation statuses in the response
     * body.
     */
    public Optional<List<ShipmentCancellation>> shipmentCancellations() {
        return Optional.ofNullable(this.shipmentCancellations);
    }

    /**
     * Invalid request.
     */
    public JsonNullable<ErrorResponse> errorResponse() {
        return this.errorResponse;
    }

    public Map<String, List<String>> headers() {
        return this.headers;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * HTTP response content type for this operation
     */
    public CancelShipmentResponse withContentType(@Nonnull String contentType) {
        this.contentType = Utils.checkNotNull(contentType, "contentType");
        return this;
    }


    /**
     * HTTP response status code for this operation
     */
    public CancelShipmentResponse withStatusCode(int statusCode) {
        this.statusCode = statusCode;
        return this;
    }


    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public CancelShipmentResponse withRawResponse(@Nonnull HttpResponse<Blob> rawResponse) {
        this.rawResponse = Utils.checkNotNull(rawResponse, "rawResponse");
        return this;
    }


    /**
     * The request was processed successfully. Check the shipment cancellation statuses in the response
     * body.
     */
    public CancelShipmentResponse withShipmentCancellations(@Nullable List<ShipmentCancellation> shipmentCancellations) {
        this.shipmentCancellations = shipmentCancellations;
        return this;
    }


    /**
     * Invalid request.
     */
    public CancelShipmentResponse withErrorResponse(@Nullable ErrorResponse errorResponse) {
        this.errorResponse = JsonNullable.of(errorResponse);
        return this;
    }


    public CancelShipmentResponse withHeaders(@Nonnull Map<String, List<String>> headers) {
        this.headers = Utils.checkNotNull(headers, "headers");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CancelShipmentResponse other = (CancelShipmentResponse) o;
        return 
            Utils.enhancedDeepEquals(this.contentType, other.contentType) &&
            Utils.enhancedDeepEquals(this.statusCode, other.statusCode) &&
            Utils.enhancedDeepEquals(this.rawResponse, other.rawResponse) &&
            Utils.enhancedDeepEquals(this.shipmentCancellations, other.shipmentCancellations) &&
            Utils.enhancedDeepEquals(this.errorResponse, other.errorResponse) &&
            Utils.enhancedDeepEquals(this.headers, other.headers);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            contentType, statusCode, rawResponse,
            shipmentCancellations, errorResponse, headers);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CancelShipmentResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "shipmentCancellations", shipmentCancellations,
                "errorResponse", errorResponse,
                "headers", headers);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String contentType;

        private int statusCode;

        private HttpResponse<Blob> rawResponse;

        private List<ShipmentCancellation> shipmentCancellations;

        private JsonNullable<ErrorResponse> errorResponse;

        private Map<String, List<String>> headers;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(@Nonnull String contentType) {
            this.contentType = Utils.checkNotNull(contentType, "contentType");
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(@Nonnull HttpResponse<Blob> rawResponse) {
            this.rawResponse = Utils.checkNotNull(rawResponse, "rawResponse");
            return this;
        }

        /**
         * The request was processed successfully. Check the shipment cancellation statuses in the response
         * body.
         */
        public Builder shipmentCancellations(@Nullable List<ShipmentCancellation> shipmentCancellations) {
            this.shipmentCancellations = shipmentCancellations;
            return this;
        }

        /**
         * Invalid request.
         */
        public Builder errorResponse(@Nullable ErrorResponse errorResponse) {
            this.errorResponse = JsonNullable.of(errorResponse);
            return this;
        }

        public Builder headers(@Nonnull Map<String, List<String>> headers) {
            this.headers = Utils.checkNotNull(headers, "headers");
            return this;
        }

        public CancelShipmentResponse build() {
            return new CancelShipmentResponse(
                contentType, statusCode, rawResponse,
                shipmentCancellations, errorResponse, headers);
        }

    }
}
