/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package pl.postivo.sdk.models.operations.async;

import static pl.postivo.sdk.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nullable;
import java.util.concurrent.CompletableFuture;
import pl.postivo.sdk.SDKConfiguration;
import pl.postivo.sdk.models.operations.DeleteSenderRequest;
import pl.postivo.sdk.operations.DeleteSender;
import pl.postivo.sdk.utils.Headers;
import pl.postivo.sdk.utils.Options;
import pl.postivo.sdk.utils.RetryConfig;
import pl.postivo.sdk.utils.Utils;

public class DeleteSenderRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final DeleteSenderRequest.Builder pojoBuilder;
    private DeleteSenderRequest request;
    private final Options.Builder optionsBuilder;
    private boolean _setterCalled;

    public DeleteSenderRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = DeleteSenderRequest.builder();
        this.optionsBuilder = Options.builder();
    }

    public DeleteSenderRequestBuilder id(long id) {
        this.pojoBuilder.id(id);
        this._setterCalled = true;
        return this;
    }

    public DeleteSenderRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    private DeleteSenderRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public DeleteSenderRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<DeleteSenderResponse> call() {
        Options options = optionsBuilder.build();
        AsyncRequestOperation<DeleteSenderRequest, DeleteSenderResponse> operation
              = new DeleteSender.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
}
