/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package pl.postivo.sdk.models.operations.async;

import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.io.InputStream;
import java.lang.Override;
import java.lang.String;
import java.net.http.HttpResponse;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;
import pl.postivo.sdk.models.components.ErrorResponse;
import pl.postivo.sdk.utils.AsyncResponse;
import pl.postivo.sdk.utils.Blob;
import pl.postivo.sdk.utils.Utils;


public class PingResponse implements AsyncResponse {
    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<Blob> rawResponse;

    /**
     * API service is available.
     */
    private pl.postivo.sdk.models.components.PingResponse pingResponse;

    /**
     * Invalid request.
     */
    private JsonNullable<ErrorResponse> errorResponse;

    @JsonCreator
    public PingResponse(
            @Nonnull String contentType,
            int statusCode,
            @Nonnull HttpResponse<Blob> rawResponse,
            @Nullable pl.postivo.sdk.models.components.PingResponse pingResponse,
            @Nullable JsonNullable<ErrorResponse> errorResponse) {
        this.contentType = Optional.ofNullable(contentType)
            .orElseThrow(() -> new IllegalArgumentException("contentType cannot be null"));
        this.statusCode = statusCode;
        this.rawResponse = Optional.ofNullable(rawResponse)
            .orElseThrow(() -> new IllegalArgumentException("rawResponse cannot be null"));
        this.pingResponse = pingResponse;
        this.errorResponse = Optional.ofNullable(errorResponse)
            .orElse(JsonNullable.undefined());
    }
    
    public PingResponse(
            @Nonnull String contentType,
            int statusCode,
            @Nonnull HttpResponse<Blob> rawResponse) {
        this(contentType, statusCode, rawResponse,
            null, null);
    }

    /**
     * HTTP response content type for this operation
     */
    public String contentType() {
        return this.contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    public int statusCode() {
        return this.statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public HttpResponse<Blob> rawResponse() {
        return this.rawResponse;
    }

    /**
     * API service is available.
     */
    public Optional<pl.postivo.sdk.models.components.PingResponse> pingResponse() {
        return Optional.ofNullable(this.pingResponse);
    }

    /**
     * Invalid request.
     */
    public JsonNullable<ErrorResponse> errorResponse() {
        return this.errorResponse;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * HTTP response content type for this operation
     */
    public PingResponse withContentType(@Nonnull String contentType) {
        this.contentType = Utils.checkNotNull(contentType, "contentType");
        return this;
    }


    /**
     * HTTP response status code for this operation
     */
    public PingResponse withStatusCode(int statusCode) {
        this.statusCode = statusCode;
        return this;
    }


    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public PingResponse withRawResponse(@Nonnull HttpResponse<Blob> rawResponse) {
        this.rawResponse = Utils.checkNotNull(rawResponse, "rawResponse");
        return this;
    }


    /**
     * API service is available.
     */
    public PingResponse withPingResponse(@Nullable pl.postivo.sdk.models.components.PingResponse pingResponse) {
        this.pingResponse = pingResponse;
        return this;
    }


    /**
     * Invalid request.
     */
    public PingResponse withErrorResponse(@Nullable ErrorResponse errorResponse) {
        this.errorResponse = JsonNullable.of(errorResponse);
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PingResponse other = (PingResponse) o;
        return 
            Utils.enhancedDeepEquals(this.contentType, other.contentType) &&
            Utils.enhancedDeepEquals(this.statusCode, other.statusCode) &&
            Utils.enhancedDeepEquals(this.rawResponse, other.rawResponse) &&
            Utils.enhancedDeepEquals(this.pingResponse, other.pingResponse) &&
            Utils.enhancedDeepEquals(this.errorResponse, other.errorResponse);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            contentType, statusCode, rawResponse,
            pingResponse, errorResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PingResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "pingResponse", pingResponse,
                "errorResponse", errorResponse);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String contentType;

        private int statusCode;

        private HttpResponse<Blob> rawResponse;

        private pl.postivo.sdk.models.components.PingResponse pingResponse;

        private JsonNullable<ErrorResponse> errorResponse;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(@Nonnull String contentType) {
            this.contentType = Utils.checkNotNull(contentType, "contentType");
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(@Nonnull HttpResponse<Blob> rawResponse) {
            this.rawResponse = Utils.checkNotNull(rawResponse, "rawResponse");
            return this;
        }

        /**
         * API service is available.
         */
        public Builder pingResponse(@Nullable pl.postivo.sdk.models.components.PingResponse pingResponse) {
            this.pingResponse = pingResponse;
            return this;
        }

        /**
         * Invalid request.
         */
        public Builder errorResponse(@Nullable ErrorResponse errorResponse) {
            this.errorResponse = JsonNullable.of(errorResponse);
            return this;
        }

        public PingResponse build() {
            return new PingResponse(
                contentType, statusCode, rawResponse,
                pingResponse, errorResponse);
        }

    }
}
