/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package pl.postivo.sdk.models.operations.async;

import static pl.postivo.sdk.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.util.concurrent.CompletableFuture;
import pl.postivo.sdk.SDKConfiguration;
import pl.postivo.sdk.models.components.Shipment;
import pl.postivo.sdk.operations.ShipmentPrice;
import pl.postivo.sdk.utils.Headers;
import pl.postivo.sdk.utils.Options;
import pl.postivo.sdk.utils.RetryConfig;
import pl.postivo.sdk.utils.Utils;

public class ShipmentPriceRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private Shipment request;
    private final Options.Builder optionsBuilder;

    public ShipmentPriceRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.optionsBuilder = Options.builder();
    }

    public ShipmentPriceRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    public ShipmentPriceRequestBuilder request(@Nonnull Shipment request) {
        this.request = Utils.checkNotNull(request, "request");
        return this;
    }

    private Shipment _buildRequest() {
        return this.request;
    }
    
    public ShipmentPriceRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<ShipmentPriceResponse> call() {
        Options options = optionsBuilder.build();
        AsyncRequestOperation<Shipment, ShipmentPriceResponse> operation
              = new ShipmentPrice.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
}
