/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package pl.postivo.sdk.models.operations.async;

import static pl.postivo.sdk.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.util.concurrent.CompletableFuture;
import pl.postivo.sdk.SDKConfiguration;
import pl.postivo.sdk.models.components.Contact;
import pl.postivo.sdk.models.operations.UpdateContactRequest;
import pl.postivo.sdk.operations.UpdateContact;
import pl.postivo.sdk.utils.Headers;
import pl.postivo.sdk.utils.Options;
import pl.postivo.sdk.utils.RetryConfig;
import pl.postivo.sdk.utils.Utils;

public class UpdateContactRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final UpdateContactRequest.Builder pojoBuilder;
    private UpdateContactRequest request;
    private final Options.Builder optionsBuilder;
    private boolean _setterCalled;

    public UpdateContactRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = UpdateContactRequest.builder();
        this.optionsBuilder = Options.builder();
    }

    public UpdateContactRequestBuilder id(long id) {
        this.pojoBuilder.id(id);
        this._setterCalled = true;
        return this;
    }

    public UpdateContactRequestBuilder contact(@Nonnull Contact contact) {
        this.pojoBuilder.contact(contact);
        this._setterCalled = true;
        return this;
    }

    public UpdateContactRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    private UpdateContactRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public UpdateContactRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<UpdateContactResponse> call() {
        Options options = optionsBuilder.build();
        AsyncRequestOperation<UpdateContactRequest, UpdateContactResponse> operation
              = new UpdateContact.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
}
